import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {load,readJSON,write,stats,esc,slug,root} from './lib.mjs';
import {buildIntelligence,DATASET_VERSION,CALCULATED_AT} from './intelligence.mjs';
import {buildSourceRegistry,buildKnowledgeGraph,factDisplay,sourceQuality,SCHEMA_VERSION} from './governance.mjs';

const {entities,taxonomy,semantic,taxonomyAliases,roleMappings,definitions}=await load();
const rawRelationships=await readJSON('data/relationships/relationships.json');
const cfoTaxonomy=await readJSON('data/taxonomy/cfo.json');
const cfoGuides=await readJSON('data/guides/cfo.json');
const expansion=await readJSON('data/expansions/2026-08-supplied.json');
const resolutionV050=await readJSON('data/reconciliation-v050.json');
const s=stats(entities);
const intelligence=buildIntelligence(entities);
const sourceRegistry=buildSourceRegistry(entities);
const knowledgeGraph=buildKnowledgeGraph(entities,rawRelationships,sourceRegistry);
const sourceMetrics=sourceQuality(entities,sourceRegistry);
const byId=new Map(entities.map(entity=>[entity.id,entity]));
const relationsBySubject=Object.groupBy(knowledgeGraph.relationships,relationship=>relationship.subject_entity_id);
const derivedMetricCount=intelligence.market_maps.reduce((count,map)=>count+1+map.buckets.length,0)+intelligence.benchmarks.reduce((count,benchmark)=>count+(benchmark.metrics?.length||1),0);
const buildCommit=(process.env.GITHUB_SHA||process.env.BUILD_COMMIT||execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim()).slice(0,40);
const releaseLabel=`v${DATASET_VERSION}`;
for(const folder of ['entities','providers','formats','intelligence','industries'])await fs.rm(path.join(root,'docs',folder),{recursive:true,force:true});
await fs.rm(path.join(root,'docs/data/quality'),{recursive:true,force:true});
const assetDir=path.join(root,'docs/assets');
for(const file of await fs.readdir(assetDir))if(/^(style|app)\.[a-f0-9]{10}\.(css|js)$/.test(file))await fs.rm(path.join(assetDir,file));
const hashAsset=async file=>{const content=await fs.readFile(path.join(assetDir,file));const extension=path.extname(file);const base=path.basename(file,extension);const hash=crypto.createHash('sha256').update(content).digest('hex').slice(0,10);const output=`${base}.${hash}${extension}`;await fs.writeFile(path.join(assetDir,output),content);return output;};
const styleAsset=await hashAsset('style.css');
const appAsset=await hashAsset('app.js');
const dimensions=['provider_types','community_formats','event_formats','intelligence_types','resource_types','executive_needs','topics','audiences'];
const vocab=new Map(Object.entries(semantic).flatMap(([dimension,items])=>items.map(item=>[`${dimension}:${item.id}`,item])));
const labels=(dimension,ids=[])=>ids.map(id=>vocab.get(`${dimension}:${id}`)?.label||id);
const semanticRelationConfig=[
 ['cxo_roles','serves_role','role','cxo_roles'],['provider_types','provides_type','provider_type','categories'],['community_formats','offers_community_format','community_format','community_formats'],['event_formats','offers_event_format','event_format','event_formats'],['intelligence_types','publishes_intelligence','intelligence_type','intelligence_types'],['resource_types','provides_resource','resource_type','resource_types'],['executive_needs','supports_need','executive_need','executive_needs'],['topics','addresses_topic','topic','topics'],['audiences','serves_audience','audience','audiences'],['geographies','operates_in','geography','geographies']
];
const semanticLabel=(field,id)=>field==='cxo_roles'||field==='geographies'?id:field==='provider_types'?taxonomy.categories.find(category=>slug(category)===id)||id:vocab.get(`${field}:${id}`)?.label||id;
const semanticAssociationCandidates=entities.flatMap(entity=>semanticRelationConfig.flatMap(([field,predicate,objectDimension,sourceField])=>(entity[field]||[]).map(id=>{
 const evidenceUrls=[...(entity.sources||[]).filter(source=>(source.supports||[]).includes(sourceField)).map(source=>source.url),...(entity.classification_evidence||[]).filter(evidence=>(evidence.supports||[]).includes(field)).map(evidence=>evidence.url)];
 return {id:`sem_${entity.id}_${predicate}_${slug(id)}`,subject_entity_id:entity.id,predicate,object_dimension:objectDimension,object_id:id,object_label:semanticLabel(field,id),evidence_urls:[...new Set(evidenceUrls)],verification_status:evidenceUrls.length?'evidence-linked':'source pending'};
})));
const semanticRelationships=semanticAssociationCandidates.filter(relationship=>relationship.evidence_urls.length);
const semanticRelationshipCoverage={total_classified_associations:semanticAssociationCandidates.length,evidence_linked_relationships:semanticRelationships.length,associations_pending_field_specific_evidence:semanticAssociationCandidates.length-semanticRelationships.length};
const semanticRelationsBySubject=Object.groupBy(semanticRelationships,relationship=>relationship.subject_entity_id);
const q=value=>`"${String(value??'').replaceAll('"','""')}"`;
const cols=['id','name','slug','entity_type','website','cxo_roles','categories',...dimensions,'industries','geographies','verification_status','last_verified'];
const csv=[cols.join(','),...entities.map(entity=>cols.map(key=>q(Array.isArray(entity[key])?entity[key].join('|'):entity[key])).join(','))].join('\n')+'\n';
const searchIndexPayload=JSON.stringify(entities.map(entity=>({id:entity.id,name:entity.name,slug:entity.slug,aliases:entity.aliases||[],categories:entity.categories,cxo_roles:entity.cxo_roles,community_formats:entity.community_formats,event_formats:entity.event_formats,intelligence_types:entity.intelligence_types,resource_types:entity.resource_types,executive_needs:entity.executive_needs,topics:entity.topics,audiences:entity.audiences,geographies:entity.geographies})));
const searchIndexHash=crypto.createHash('sha256').update(searchIndexPayload).digest('hex').slice(0,10);
const searchIndexFile=`search-index.${searchIndexHash}.json`;
const releaseFingerprintFields={dataset_version:DATASET_VERSION,schema_version:SCHEMA_VERSION,build_commit:buildCommit,organizations:s.entities,sourced_facts:s.sourced_facts,canonical_sources:sourceRegistry.length};
const releaseFingerprint=crypto.createHash('sha256').update(JSON.stringify(releaseFingerprintFields)).digest('hex');
const statistics={...s,dataset_version:DATASET_VERSION,schema_version:SCHEMA_VERSION,build_commit:buildCommit,release_fingerprint:releaseFingerprint,last_dataset_update:CALCULATED_AT,canonical_sources:sourceRegistry.length,sourced_relationships:knowledgeGraph.sourced_relationship_count,semantic_relationships:semanticRelationships.length,derived_relationships:knowledgeGraph.derived_reciprocal_count,derived_metrics:derivedMetricCount};
const buildManifest={project:'CXO Ecosystem Index',dataset_version:DATASET_VERSION,schema_version:SCHEMA_VERSION,build_commit:buildCommit,release_fingerprint:releaseFingerprint,fingerprint_fields:releaseFingerprintFields,generated_at:s.generated_at,last_dataset_update:CALCULATED_AT,organizations:s.entities,sourced_facts:s.sourced_facts,canonical_sources:sourceRegistry.length,verified_entities:s.verified_entities,provider_categories:s.provider_categories,cxo_functions:s.cxo_functions,geographic_markets:s.geographies,sourced_relationships:knowledgeGraph.sourced_relationship_count,semantic_relationships:semanticRelationships.length,derived_relationships:knowledgeGraph.derived_reciprocal_count,derived_metrics:derivedMetricCount,canonical_url:'https://openfutureforum.github.io/cxo-ecosystem-index/',data_url:'https://openfutureforum.github.io/cxo-ecosystem-index/data.html',search_index_url:`https://openfutureforum.github.io/cxo-ecosystem-index/data/${searchIndexFile}`};
const latest={kind:'Current Release Manifest',purpose:'Programmatic version discovery, debugging, provenance and external data consumers.',dataset_version:DATASET_VERSION,schema_version:SCHEMA_VERSION,build_commit:buildCommit,release_fingerprint:releaseFingerprint,organizations:s.entities,sourced_facts:s.sourced_facts,canonical_sources:sourceRegistry.length,generated_at:s.generated_at,last_dataset_update:CALCULATED_AT,canonical_url:buildManifest.canonical_url,data_url:buildManifest.data_url,manifest_url:'https://openfutureforum.github.io/cxo-ecosystem-index/data/build-manifest.json',search_index_url:buildManifest.search_index_url};

await write('data/exports/entities.json',JSON.stringify({schema_version:SCHEMA_VERSION,dataset_version:DATASET_VERSION,build_commit:buildCommit,generated_at:s.generated_at,dimensions,entities},null,2)+'\n');
await write('data/exports/entities.csv',csv);
await write('docs/data/entities.json',JSON.stringify(entities));
await write('docs/data/statistics.json',JSON.stringify(statistics,null,2));
await write('docs/data/build-manifest.json',JSON.stringify(buildManifest,null,2));
await write('docs/data/latest.json',JSON.stringify(latest,null,2));
await write('data/exports/build-manifest.json',JSON.stringify(buildManifest,null,2)+'\n');
await write('data/exports/latest.json',JSON.stringify(latest,null,2)+'\n');
await write('docs/data/definitions.json',JSON.stringify(definitions,null,2));
await write('docs/data/taxonomy.json',JSON.stringify(semantic,null,2));
await write('docs/data/taxonomy-aliases.json',JSON.stringify(taxonomyAliases,null,2));
await write('docs/data/role-mappings.json',JSON.stringify(roleMappings,null,2));
await write('data/exports/taxonomy.json',JSON.stringify({dataset_version:DATASET_VERSION,semantic,aliases:taxonomyAliases,role_mappings:roleMappings},null,2)+'\n');
await write('data/exports/role-mappings.json',JSON.stringify(roleMappings,null,2)+'\n');
await write('docs/data/entities.csv',csv);
await write('data/exports/intelligence.json',JSON.stringify(intelligence,null,2)+'\n');
await write('data/exports/market-maps.json',JSON.stringify({dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,market_maps:intelligence.market_maps},null,2)+'\n');
await write('data/exports/comparisons.json',JSON.stringify({dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,comparisons:intelligence.comparisons},null,2)+'\n');
await write('data/exports/benchmarks.json',JSON.stringify({dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,benchmarks:intelligence.benchmarks},null,2)+'\n');
await write('data/exports/data-quality.json',JSON.stringify(intelligence.benchmarks.find(item=>item.id==='data-quality'),null,2)+'\n');
await write('docs/data/intelligence.json',JSON.stringify(intelligence,null,2));
await write('docs/data/market-maps.json',JSON.stringify(intelligence.market_maps,null,2));
await write('docs/data/comparisons.json',JSON.stringify(intelligence.comparisons,null,2));
await write('docs/data/benchmarks.json',JSON.stringify(intelligence.benchmarks,null,2));
await write('docs/data/data-quality.json',JSON.stringify(intelligence.benchmarks.find(item=>item.id==='data-quality'),null,2));
const factExport=entities.flatMap(entity=>entity.facts.map(fact=>({...fact,entity_id:entity.id})));
const graphExport={dataset_version:DATASET_VERSION,schema_version:SCHEMA_VERSION,build_commit:buildCommit,generated_at:CALCULATED_AT,entities,facts:factExport,relationships:knowledgeGraph.relationships,semantic_relationships:semanticRelationships,semantic_relationship_coverage:semanticRelationshipCoverage,sources:sourceRegistry,taxonomy:{core:taxonomy,semantic,aliases:taxonomyAliases,role_mappings:roleMappings},definitions};
await write('data/exports/sources.json',JSON.stringify({dataset_version:DATASET_VERSION,schema_version:'1.0.0',sources:sourceRegistry},null,2)+'\n');
await write('data/exports/facts.json',JSON.stringify({dataset_version:DATASET_VERSION,schema_version:SCHEMA_VERSION,facts:factExport},null,2)+'\n');
await write('data/exports/relationships.json',JSON.stringify(knowledgeGraph,null,2)+'\n');
await write('data/exports/semantic-relationships.json',JSON.stringify({dataset_version:DATASET_VERSION,schema_version:'1.0.0',coverage:semanticRelationshipCoverage,relationships:semanticRelationships},null,2)+'\n');
await write('data/exports/knowledge-graph.json',JSON.stringify(graphExport,null,2)+'\n');
await write('docs/data/sources.json',JSON.stringify(sourceRegistry));
await write('docs/data/facts.json',JSON.stringify(factExport));
await write('docs/data/relationships.json',JSON.stringify(knowledgeGraph));
await write('docs/data/semantic-relationships.json',JSON.stringify({dataset_version:DATASET_VERSION,schema_version:'1.0.0',coverage:semanticRelationshipCoverage,relationships:semanticRelationships}));
await write('docs/data/knowledge-graph.json',JSON.stringify(graphExport));
for(const file of await fs.readdir(path.join(root,'docs/data')))if(/^search-index\.[a-f0-9]{10}\.json$/.test(file))await fs.rm(path.join(root,'docs/data',file));
await write('docs/data/search-index.json',searchIndexPayload);
await write(`docs/data/${searchIndexFile}`,searchIndexPayload);
await fs.copyFile(path.join(root,'CITATION.cff'),path.join(root,'docs/CITATION.cff'));
await fs.copyFile(path.join(root,'data/semantic-relationship.schema.json'),path.join(root,'docs/data/semantic-relationship.schema.json'));
const cohortColumns=['id','name','website','entity_type','cxo_roles','categories','headquarters','geographies','founded_year','verification_status'];
const cohortExport=async(id,members)=>{const rows=[cohortColumns.join(','),...members.map(entity=>cohortColumns.map(key=>q(Array.isArray(entity[key])?entity[key].join('|'):entity[key])).join(','))].join('\n')+'\n';const payload={dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,cohort_id:id,entity_ids:members.map(entity=>entity.id),entities:members};await write(`docs/data/cohorts/${id}.csv`,rows);await write(`docs/data/cohorts/${id}.json`,JSON.stringify(payload,null,2));await write(`data/exports/cohorts/${id}.csv`,rows);await write(`data/exports/cohorts/${id}.json`,JSON.stringify(payload,null,2)+'\n');};
const cohortMapIds=intelligence.market_maps.map(item=>item.id);
for(const map of intelligence.market_maps)await cohortExport(map.id,map.entity_ids.map(id=>byId.get(id)));
const siliconValleyEntities=entities.filter(entity=>[entity.headquarters,...entity.geographies].filter(Boolean).some(value=>/silicon valley|san francisco|palo alto|san jose|bay area/i.test(value)));
await cohortExport('silicon-valley-cxo-ecosystem',siliconValleyEntities);

const depth=title=>/^(Entity:|Guide:|Provider:|Format:|Intelligence:|Industry:)/.test(title)||['Intelligence Home','Providers Home','Industries Home'].includes(title)?'../':'';
const fixedCanonicalPaths=new Map([['Home',''],['Intelligence Home','intelligence/'],['Providers Home','providers/'],['Industries Home','industries/'],['Expansion Reconciliation Report','reconciliation-report.html']]);
const canonicalPath=title=>fixedCanonicalPaths.has(title)?fixedCanonicalPaths.get(title):title.startsWith('Entity:')?`entities/${entities.find(entity=>entity.name===title.slice(8))?.slug||slug(title.slice(8))}.html`:title.startsWith('Guide:')?`guides/${cfoGuides.find(guide=>guide.title===title.slice(7))?.slug||slug(title.slice(7))}.html`:title.startsWith('Provider:')?`providers/${slug(title.slice(9))}.html`:title.startsWith('Format:')?`formats/${slug(title.slice(7))}.html`:title.startsWith('Intelligence:')?`intelligence/${slug(title.slice(13))}.html`:title.startsWith('Industry:')?`industries/${slug(title.slice(9))}.html`:`${slug(title)}.html`;
const labelForTitle=title=>title.replace(/^(Entity|Guide|Provider|Format|Intelligence|Industry):\s*/, '').replace(/ Home$/,'');
const breadcrumbParents=title=>title.startsWith('Provider:')?[['Providers','providers/']]:title.startsWith('Intelligence:')?[['Intelligence','intelligence/']]:title.startsWith('Industry:')?[['Industries','industries/']]:title.startsWith('Guide:')?[['Research','cfo-guides.html']]:title.endsWith(' Ecosystem')&&title!=='CXO Ecosystems'?[['CXO Ecosystems','cxo-ecosystems.html']]:[];
const breadcrumbs=title=>{if(title==='Home')return {html:'',json:null};const items=[['Home',''],...breadcrumbParents(title),[labelForTitle(title),canonicalPath(title)]];const prefix=depth(title);const html=`<nav class="crumb" aria-label="Breadcrumb">${items.map(([label,url],index)=>index===items.length-1?`<span aria-current="page">${esc(label)}</span>`:`<a href="${prefix}${url||'index.html'}">${esc(label)}</a>`).join(' / ')}</nav>`;const json={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items.map(([name,url],index)=>({'@type':'ListItem',position:index+1,name,item:`https://openfutureforum.github.io/cxo-ecosystem-index/${url}`}))};return {html,json};};
const modifiedFor=title=>{if(title.startsWith('Entity:')){const entity=entities.find(item=>item.name===title.slice(8));return entity?.facts?.map(fact=>fact.last_verified).filter(Boolean).sort().at(-1)||entity?.last_verified||null;}if(title.startsWith('Guide:'))return cfoGuides.find(guide=>guide.title===title.slice(7))?.updated||null;if(['Methodology','Expansion Reconciliation Report','v050 Report'].includes(title))return null;return CALCULATED_AT;};
const shell=(title,body,description='Open-source intelligence for the C-suite.',pageTitle=title)=>{const canonical=`https://openfutureforum.github.io/cxo-ecosystem-index/${canonicalPath(title)}`;const displayTitle=title==='Home'?'CXO Ecosystem Index | C-Suite Companies, Communities & Advisors':`${pageTitle} | CXO Ecosystem Index`;const crumb=breadcrumbs(title);const modified=modifiedFor(title);const modifiedProperties=modified?{dateModified:modified}:{};const pageLd=title==='Home'?{'@context':'https://schema.org','@graph':[{'@type':'WebSite',name:'CXO Ecosystem Index',url:canonical,description},{'@type':'DataCatalog',name:'CXO Ecosystem Index',url:canonical,dataset:'https://openfutureforum.github.io/cxo-ecosystem-index/data.html',...modifiedProperties}]}:{'@context':'https://schema.org','@graph':[{'@type':'WebPage',name:pageTitle,url:canonical,description,...modifiedProperties},...(crumb.json?[crumb.json]:[])]};const modifiedMeta=modified?`<meta name="last-modified" content="${modified}">`:'';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(displayTitle)}</title><meta name="description" content="${esc(description)}">${modifiedMeta}<link rel="canonical" href="${canonical}"><meta property="og:title" content="${esc(displayTitle)}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="stylesheet" href="${depth(title)}assets/${styleAsset}"><script type="application/ld+json">${JSON.stringify(pageLd)}</script></head><body><header><a class="brand" href="${depth(title)}index.html"><b>CXO</b> Ecosystem Index</a><nav><a href="${depth(title)}index.html#explore">Explore</a><a href="${depth(title)}cxo-ecosystems.html">CXO Ecosystems</a><a href="${depth(title)}providers/">Providers</a><a href="${depth(title)}intelligence/">Intelligence</a><a href="${depth(title)}cfo-guides.html">Research</a><a href="${depth(title)}data.html">Data</a><a href="${depth(title)}methodology.html">Methodology</a></nav></header><main>${crumb.html}${body}</main><footer><p>Independent structured index maintained by Open Future Forum. Inclusion does not imply endorsement.</p><p>Dataset ${releaseLabel} · Schema ${SCHEMA_VERSION} · Updated ${CALCULATED_AT}</p><p><a href="https://openfutureforum.github.io/executive-communities-index/">Executive Communities Index</a> · <a href="https://openfutureforum.github.io/executive-community-playbook/">Executive Community Playbook</a></p></footer></body></html>`;};

const entityCard=entity=>`<article class="card" data-name="${esc(entity.name.toLowerCase())}" data-cxo="${esc(entity.cxo_roles.join('|'))}" data-provider="${esc(entity.provider_types.join('|'))}" data-format="${esc([...entity.community_formats,...entity.event_formats].join('|'))}" data-topic="${esc(entity.topics.join('|'))}" data-need="${esc(entity.executive_needs.join('|'))}" data-geo="${esc(entity.geographies.join('|'))}"><div class="eyebrow">${esc(entity.entity_type)}</div><h3><a href="entities/${entity.slug}.html">${esc(entity.name)}</a></h3><p>${esc(entity.description)}</p><div class="tags">${entity.cxo_roles.slice(0,4).map(x=>`<span>${esc(x)}</span>`).join('')}</div><small>${esc(entity.categories.join(' · '))}</small></article>`;
const entityCards=entities.map(entityCard).join('');
const statCards=Object.entries({Organizations:s.entities,'Sourced facts':s.sourced_facts,'Verified entities':s.verified_entities,'Canonical sources':sourceRegistry.length,'Sourced relationships':knowledgeGraph.sourced_relationship_count,'Derived metrics':derivedMetricCount,'CXO functions':s.cxo_functions,'Provider categories':s.provider_categories,'Geographic markets':s.geographies}).map(([key,value])=>`<div><strong>${value}</strong><span>${key}</span></div>`).join('');
const select=(label,id,options)=>`<label>${label}<select id="${id}"><option value="">All</option>${options.map(x=>`<option value="${esc(typeof x==='string'?x:x.id)}">${esc(typeof x==='string'?x:x.label)}</option>`).join('')}</select></label>`;

const groupByTerm=(field,minimum)=>Object.entries(Object.groupBy(entities.flatMap(entity=>entity[field].map(id=>({id,entity}))),item=>item.id)).map(([id,items])=>({id,entities:items.map(item=>item.entity)})).filter(group=>group.entities.length>=minimum).sort((a,b)=>b.entities.length-a.entities.length||a.id.localeCompare(b.id));
const providerGroups=groupByTerm('provider_types',4);
const formatGroups=groupByTerm('community_formats',3);
const termTitle=id=>id.split('-').map(word=>({ai:'AI',cfo:'CFO',hr:'HR',m:'M'}[word]||word[0].toUpperCase()+word.slice(1))).join(' ').replace('M A','M&A');
const browseLinks=[...providerGroups.map(group=>`<a href="providers/${group.id}.html">${esc(termTitle(group.id))} <small>${group.entities.length}</small></a>`),...formatGroups.map(group=>`<a href="formats/${group.id}.html">${esc(vocab.get(`community_formats:${group.id}`)?.label||termTitle(group.id))} <small>${group.entities.length}</small></a>`)].join('');

const home=`<section class="hero"><div class="eyebrow">OPEN-SOURCE C-SUITE INTELLIGENCE</div><h1>CXO Ecosystem Index</h1><p>Open-source intelligence on the companies, communities, capital providers, advisors, technology platforms and institutions serving the C-suite.</p><div class="actions"><a href="#explore">Explore the index</a><a class="secondary" href="data.html">Download data</a></div><p><small>Dataset ${releaseLabel} · Schema ${SCHEMA_VERSION} · Last updated ${CALCULATED_AT}<br>Release fingerprint <code>${releaseFingerprint}</code></small></p></section><section class="stats">${statCards}</section><section id="explore"><div class="section-head"><div><div class="eyebrow">CANONICAL ENTITY INDEX</div><h2>Explore the ecosystem</h2></div><p>Filter one canonical dataset. Filter combinations are application state, not automatically generated SEO pages.</p></div><div class="filters expanded"><label>Search<input id="search" type="search" placeholder="Name, type, format, topic, or need"></label>${select('CXO role','cxo',taxonomy.cxo_roles)}${select('Provider type','provider',taxonomy.categories.map(x=>({id:slug(x),label:x})))}${select('Format','format',[...semantic.community_formats,...semantic.event_formats])}${select('Topic','topic',semantic.topics)}${select('Executive need','need',semantic.executive_needs)}${select('Geography','geo',taxonomy.geographies)}</div><p id="result-count" class="count"></p><div id="grid" class="grid">${entityCards}</div></section><section class="principles"><div><div class="eyebrow">CONTROLLED MODEL</div><h2>Explicit relationships, visible evidence.</h2></div><ol><li><b>Canonical records</b><span>One entity can serve multiple roles, formats, topics, and needs without duplicate pages.</span></li><li><b>Controlled terms</b><span>Stable IDs and neutral definitions prevent synonym drift.</span></li><li><b>Evidence</b><span>Entity associations require official or reputable support.</span></li></ol></section><script src="assets/${appAsset}"></script>`;
const homeRoleLinks=[['CEO','ceo-ecosystem.html'],['CFO','cfo-ecosystem.html'],['CMO','cmo-ecosystem.html'],['CISO','ciso-ecosystem.html'],['CIO & CTO','cio-cto-ecosystem.html'],['CHRO','chro-ecosystem.html'],['CLO & General Counsel','clo-general-counsel-ecosystem.html'],['COO','coo-ecosystem.html'],['Board','board-ecosystem.html']].map(([label,href])=>`<a href="${href}">${label}</a>`).join('');
const marketMapLinks=intelligence.market_maps.map(item=>`<a href="intelligence/${item.id}.html">${esc(item.title)}</a>`).join('');
const comparisonLinks=intelligence.comparisons.map(item=>`<a href="intelligence/compare-${item.comparison_id}.html">${esc(item.title)}</a>`).join('');
const benchmarkLinks=intelligence.benchmarks.filter(item=>item.id!=='data-quality').map(item=>`<a href="intelligence/${item.id}.html">${esc(item.title)}</a>`).join('');
const homeWithBrowse=home.replace('<section id="explore">',`<section class="prose wide"><div class="eyebrow">DIRECT DISCOVERY</div><h2>Explore by CXO</h2><div class="download">${homeRoleLinks}</div><h2>Provider categories</h2><p>Only substantial cohorts with distinct intent, structured statistics and source coverage receive canonical pages.</p><div class="download">${browseLinks}</div><h2>Market maps</h2><div class="download">${marketMapLinks}</div><h2>Comparisons</h2><div class="download">${comparisonLinks}</div><h2>Benchmarks</h2><div class="download">${benchmarkLinks}</div><h2>Data, taxonomy, methodology and quality</h2><div class="download"><a href="intelligence/">Intelligence</a><a href="industries/">Industries</a><a href="data.html">Data downloads</a><a href="taxonomy.html">Controlled taxonomy</a><a href="methodology.html">Methodology</a><a href="data-quality.html">Data quality</a><a href="cfo-guides.html">Research guides</a></div></section><section id="explore">`);
await write('docs/index.html',shell('Home',homeWithBrowse,'Open-source intelligence on the companies, communities, capital providers, advisors, technology platforms and institutions serving the C-suite.'));

for(const entity of entities){
 const facts=[['Organization type',entity.entity_type],['Common names / aliases',(entity.aliases||[]).join(', ')],['Parent company',entity.parent_company],['Relationship notes',entity.relationship_notes],['Editorial research priority',entity.editorial_priority],['Serves',entity.cxo_roles.join(', ')],['Provider types',entity.categories.join(', ')],['Industries',(entity.industries||[]).join(', ')],['Geography',entity.geographies.join(', ')],['Verification',entity.verification_status],['Last verified',entity.last_verified]].filter(([,value])=>value);
 const sections=[['Community formats',labels('community_formats',entity.community_formats)],['Event formats',labels('event_formats',entity.event_formats)],['Research & intelligence',labels('intelligence_types',entity.intelligence_types)],['Resources',labels('resource_types',entity.resource_types)],['Executive needs',labels('executive_needs',entity.executive_needs)],['Topics',labels('topics',entity.topics)],['Additional audiences',labels('audiences',entity.audiences)]];
 const semanticSections=sections.filter(([,values])=>values.length).map(([heading,values])=>`<section><h2>${heading}</h2><div class="tags large">${values.map(value=>`<span>${esc(value)}</span>`).join('')}</div></section>`).join('');
 const sources=[...entity.sources.map(x=>({id:x.id,url:x.url,title:x.title,detail:`${x.publisher} · accessed ${x.accessed_date} · supports ${x.supports.join(', ')}`})),...entity.classification_evidence.map((x,index)=>({id:`classification-source-${index+1}`,url:x.url,title:x.title,detail:`classification evidence · supports ${x.supports.join(', ')}`}))];
 const sourceList=sources.map(source=>`<li id="${esc(source.id||'classification-source')}"><a href="${esc(source.url)}">${esc(source.title)}</a><span>${esc(source.detail)}</span></li>`).join('');
 const factRows=(entity.facts||[]).map(fact=>`<tr><td>${esc(fact.field.replaceAll('_',' '))}</td><td>${esc(factDisplay(fact))}</td><td>${fact.source_ids.map(id=>`<a href="#${esc(id)}">${esc(id)}</a>`).join(', ')}</td><td>${esc(fact.as_of_date||fact.last_verified)}</td></tr>`).join('');
 const relationRows=(relationsBySubject[entity.id]||[]).map(relation=>{const related=byId.get(relation.object_entity_id);return `<tr><td>${esc(relation.predicate.replaceAll('_',' '))}</td><td><a href="${related.slug}.html">${esc(related.name)}</a></td><td>${esc(relation.status)}</td><td>${esc(relation.as_of_date||relation.valid_from||'')}</td><td>${esc(relation.source_ids.join(', '))}${relation.derived_reciprocal?' · reciprocal derived from sourced edge':''}</td></tr>`;}).join('');
 const jsonld=JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:entity.name,alternateName:entity.aliases||[],url:entity.website,description:entity.description,areaServed:entity.geographies,knowsAbout:[...new Set([...entity.categories,...labels('topics',entity.topics),...labels('intelligence_types',entity.intelligence_types),...labels('executive_needs',entity.executive_needs)])],audience:[...entity.cxo_roles.map(role=>({'@type':'Audience',audienceType:role})),...labels('audiences',entity.audiences).map(audienceType=>({'@type':'Audience',audienceType}))],parentOrganization:entity.parent_company?{'@type':'Organization',name:entity.parent_company}:undefined});
 const providerLinks=entity.provider_types.filter(id=>providerGroups.some(group=>group.id===id)).map(id=>`<a href="../providers/${id}.html">${esc(termTitle(id))}</a>`);
 const roleHref=role=>role==='CFO'?'cfo-ecosystem.html':role==='CIO'||role==='CTO'?'cio-cto-ecosystem.html':role==='CLO'||role==='General Counsel'?'clo-general-counsel-ecosystem.html':`${slug(role)}-ecosystem.html`;
 const roleDiscovery=[...new Map(entity.cxo_roles.map(role=>[roleHref(role),role])).entries()].map(([href,role])=>`<a href="../${href}">${esc(role)}</a>`);
 const mapLinks=intelligence.market_maps.filter(map=>map.entity_ids.includes(entity.id)).map(map=>`<a href="../intelligence/${map.id}.html">${esc(map.title)}</a>`);
 const relatedLinks=[...providerLinks,...roleDiscovery,...mapLinks];
 const body=`<section class="entity-head"><div class="eyebrow">${esc(entity.entity_type)}</div><h1>${esc(entity.name)}</h1><p>${esc(entity.description)}</p><a class="site-link" href="${esc(entity.website)}">Official website ↗</a></section><section class="entity-layout"><div><h2>Structured facts</h2><dl>${facts.map(([a,b])=>`<dt>${a}</dt><dd>${esc(b)}</dd>`).join('')}</dl></div><div><h2>Inclusion basis</h2><p>${esc(entity.inclusion_basis.join(' '))}</p><h2>Products and services</h2><p>${esc([...(entity.products||[]),...(entity.services||[])].join(', ')||'Not recorded.')}</p></div></section><div class="semantic-sections">${semanticSections}</div><p><small>${(semanticRelationsBySubject[entity.id]||[]).length} evidence-linked semantic relationships are available in the <a href="../data/semantic-relationships.json">semantic relationship export</a>.</small></p>${relatedLinks.length?`<section><h2>Related discovery</h2><div class="download">${relatedLinks.join('')}</div></section>`:''}<section><h2>Source-linked facts</h2><p>${entity.facts.length} structured facts are linked to the supporting source record and verification or as-of date.</p><div class="table-wrap"><table><thead><tr><th>Field</th><th>Value</th><th>Source ID</th><th>As of / verified</th></tr></thead><tbody>${factRows}</tbody></table></div></section>${relationRows?`<section><h2>Ecosystem Relationships</h2><div class="table-wrap"><table><thead><tr><th>Relationship</th><th>Organization</th><th>Status</th><th>Date</th><th>Provenance</th></tr></thead><tbody>${relationRows}</tbody></table></div></section>`:''}<section><h2>Sources</h2><ul class="sources">${sourceList}</ul></section><script type="application/ld+json">${jsonld}</script>`;
 await write(`docs/entities/${entity.slug}.html`,shell(`Entity: ${entity.name}`,body,entity.description,`${entity.name} | ${entity.categories.slice(0,2).join(' & ')}`));
}

const cfoEntities=entities.filter(entity=>entity.cxo_roles.includes('CFO'));
const topicList=items=>`<div class="topic-grid">${items.map(item=>`<span>${esc(typeof item==='string'?item:item.name)}</span>`).join('')}</div>`;
const roleMappingById=new Map(roleMappings.mappings.map(mapping=>[mapping.id,mapping]));
const mappingLens=id=>{const mapping=roleMappingById.get(id);if(!mapping)return '';const groups=[['Community formats','community_formats',mapping.community_format_ids],['Event formats','event_formats',mapping.event_format_ids],['Research & intelligence','intelligence_types',mapping.intelligence_type_ids],['Executive needs','executive_needs',mapping.executive_need_ids],['Topics','topics',mapping.topic_ids],['Audiences','audiences',mapping.audience_ids]].filter(([,dimension,ids])=>ids?.length).map(([heading,dimension,ids])=>`<div><h3>${heading}</h3><div class="tags large">${labels(dimension,ids).map(label=>`<span>${esc(label)}</span>`).join('')}</div></div>`).join('');return `<section><h2>Taxonomy lens</h2><p>This lens identifies controlled concepts relevant to the ${esc(mapping.label)}. It does not claim that every listed organization offers every format, resource, or outcome.</p><div class="semantic-sections">${groups}</div></section>`;};
await write('docs/cfo-ecosystem.html',shell('CFO Ecosystem',`<section class="prose wide"><div class="eyebrow">EXPLORE BY CXO</div><h1>CFO Ecosystem</h1><p>A structured view of the companies, advisors, capital providers, communities, and technology platforms serving chief financial officers and finance organizations.</p><div class="stats compact"><div><strong>${cfoEntities.length}</strong><span>CFO-relevant entities</span></div><div><strong>${new Set(cfoEntities.flatMap(e=>e.categories)).size}</strong><span>Provider categories</span></div><div><strong>${new Set(cfoEntities.flatMap(e=>e.geographies)).size}</strong><span>Markets represented</span></div></div>${mappingLens('cfo')}<h2>Operating contexts</h2>${topicList(cfoTaxonomy.contexts)}<h2>Finance functions</h2>${topicList(cfoTaxonomy.functional_topics)}<h2>Systems and transformation</h2>${topicList(cfoTaxonomy.systems_topics)}<h2>Decision resources</h2>${topicList(cfoTaxonomy.decision_resources)}<h2>Indexed organizations</h2><div class="grid">${cfoEntities.map(entityCard).join('')}</div></section>`,'Structured intelligence on providers, systems, capital, communities, and advisors serving CFOs.'));
const rolePages=[
 {label:'CEO',roles:['CEO'],description:'Chief executives responsible for enterprise strategy, leadership, capital, growth, and board accountability.'},
 {label:'CMO',roles:['CMO'],description:'Chief marketing officers responsible for market strategy, customer acquisition, brand, growth, and marketing performance.'},
 {label:'CISO',roles:['CISO'],description:'Chief information security officers responsible for cybersecurity strategy, identity, risk, resilience, and board reporting.'},
 {label:'CIO & CTO',roles:['CIO','CTO'],description:'Technology executives responsible for enterprise systems, data, artificial intelligence, architecture, engineering, and technology strategy.'},
 {label:'CHRO',roles:['CHRO'],description:'People executives responsible for workforce strategy, talent, human resources, benefits, performance, and organizational development.'},
 {label:'CLO & General Counsel',roles:['CLO','General Counsel'],description:'Senior legal executives responsible for corporate law, governance, transactions, regulation, disputes, privacy, and legal operations.'},
 {label:'COO',roles:['COO'],description:'Operating executives responsible for organizational execution, processes, systems, delivery, and performance.'},
 {label:'Board',roles:['Board'],description:'Board directors and governance leaders responsible for oversight, accountability, succession, risk, and long-term enterprise stewardship.'}
];
for(const group of rolePages){const roleEntities=entities.filter(entity=>group.roles.some(role=>entity.cxo_roles.includes(role)));const roleSlug=slug(group.label);await write(`docs/${roleSlug}-ecosystem.html`,shell(`${group.label} Ecosystem`,`<section class="prose wide"><div class="eyebrow">EXPLORE BY CXO</div><h1>${group.label} Ecosystem</h1><p>${esc(group.description)}</p><p>This canonical role page contains ${roleEntities.length} evidence-backed organizations across ${new Set(roleEntities.flatMap(e=>e.categories)).size} provider categories. Related titles are normalized into one functional hub where appropriate.</p>${mappingLens(roleSlug)}<h2>Indexed organizations</h2><div class="grid">${roleEntities.map(entityCard).join('')}</div></section>`,`Structured index of organizations serving ${group.label} leaders.`));}
const roleLinks=[{label:'CFO',href:'cfo-ecosystem.html',count:cfoEntities.length},...rolePages.map(group=>({label:group.label,href:`${slug(group.label)}-ecosystem.html`,count:entities.filter(entity=>group.roles.some(role=>entity.cxo_roles.includes(role))).length}))];
await write('docs/cxo-ecosystems.html',shell('CXO Ecosystems',`<section class="prose wide"><div class="eyebrow">FUNCTIONAL ECOSYSTEMS</div><h1>CXO Ecosystems</h1><p>Browse evidence-backed provider landscapes by executive function. CLO and General Counsel are normalized into one legal-leadership ecosystem; CIO and CTO share one technology-leadership ecosystem.</p><div class="grid">${roleLinks.map(item=>`<article class="card"><h3><a href="${item.href}">${esc(item.label)} Ecosystem</a></h3><p>${item.count} indexed organizations.</p></article>`).join('')}</div></section>`,'Evidence-backed provider ecosystems for executive functions.'));

for(const group of providerGroups){
 const label=termTitle(group.id);const roles=[...new Set(group.entities.flatMap(entity=>entity.cxo_roles))];const markets=[...new Set(group.entities.flatMap(entity=>entity.geographies))];
 const primaryCount=group.entities.filter(entity=>entity.sources.some(source=>['official company','official organization','government','regulatory','investor relations'].includes(source.source_class))).length;
 const aiCount=group.entities.filter(entity=>entity.categories.some(category=>['Artificial Intelligence','AI Agents','AI Infrastructure','AI Security'].includes(category))).length;
 const roleCounts=Object.entries(Object.groupBy(group.entities.flatMap(entity=>entity.cxo_roles),role=>role)).map(([role,items])=>[role,items.length]).sort((a,b)=>b[1]-a[1]);
 const subcategoryCounts=Object.entries(Object.groupBy(group.entities.flatMap(entity=>entity.categories.filter(category=>slug(category)!==group.id)),category=>category)).map(([category,items])=>[category,items.length]).sort((a,b)=>b[1]-a[1]).slice(0,8);
 const providerRoleHref=role=>role==='CFO'?'cfo-ecosystem.html':role==='CIO'||role==='CTO'?'cio-cto-ecosystem.html':role==='CLO'||role==='General Counsel'?'clo-general-counsel-ecosystem.html':`${slug(role)}-ecosystem.html`;
 const relatedRoleLinks=roleCounts.slice(0,5).map(([role])=>`<a href="../${providerRoleHref(role)}">${esc(role)} ecosystem</a>`).join('');
 const relatedMapLinks=intelligence.market_maps.filter(map=>map.entity_ids.some(id=>group.entities.some(entity=>entity.id===id))).map(map=>`<a href="../intelligence/${map.id}.html">${esc(map.title)}</a>`).join('');
 const cohortMap=intelligence.market_maps.find(map=>map.id===group.id);
 const downloads=cohortMap?`<a href="../data/cohorts/${group.id}.csv">Cohort CSV</a><a href="../data/cohorts/${group.id}.json">Cohort JSON</a>`:'';
 const body=`<section class="prose wide"><div class="eyebrow">PROVIDER TYPE</div><h1>${esc(label)}</h1><p>An evidence-backed view of organizations classified as ${esc(label.toLowerCase())} providers in the CXO Ecosystem Index.</p><div class="stats compact"><div><strong>${group.entities.length}</strong><span>Organizations</span></div><div><strong>${Math.round(100*primaryCount/group.entities.length)}%</strong><span>Primary-source coverage</span></div><div><strong>${aiCount}</strong><span>AI-related providers</span></div></div>${mappingLens(group.id)}<h2>Category intelligence</h2><p><b>CXO-role distribution:</b> ${roleCounts.map(([role,count])=>`${esc(role)} ${count}`).join(' · ')}</p><p><b>Common adjacent categories:</b> ${subcategoryCounts.map(([category,count])=>`${esc(category)} ${count}`).join(' · ')||'No adjacent category recorded.'}</p><p><small>Statistics use dataset version ${DATASET_VERSION}, calculation date ${CALCULATED_AT}, and all ${group.entities.length} indexed organizations in this category as the denominator. Unknown fields are not inferred.</small></p><h2>Related intelligence and data</h2><div class="download">${relatedRoleLinks}${relatedMapLinks}${downloads}<a href="../data.html">All data downloads</a></div><h2>Indexed organizations</h2><div class="grid">${group.entities.map(entityCard).join('').replaceAll('href="entities/','href="../entities/')}</div><p><small>Inclusion is neutral and does not imply endorsement. Category membership requires cited evidence on each organization page.</small></p></section>`;
 await write(`docs/providers/${group.id}.html`,shell(`Provider: ${label}`,body,`Evidence-backed index of ${label.toLowerCase()} organizations serving executives.`,label));
}
for(const group of formatGroups){
 const term=vocab.get(`community_formats:${group.id}`);const label=term?.label||termTitle(group.id);
 const body=`<section class="prose wide"><div class="eyebrow">COMMUNITY FORMAT</div><h1>${esc(label)}</h1><p>${esc(term?.definition||`Organizations offering the ${label.toLowerCase()} format.`)}</p><p>This canonical format page includes ${group.entities.length} evidence-backed organizations. Narrower role, topic, need, and geography combinations remain filters.</p><h2>Indexed organizations</h2><div class="grid">${group.entities.map(entityCard).join('').replaceAll('href="entities/','href="../entities/')}</div><p><small>Format classification requires cited evidence on each organization page.</small></p></section>`;
 await write(`docs/formats/${group.id}.html`,shell(`Format: ${label}`,body,`Organizations offering the ${label.toLowerCase()} format.`));
}

const providerHubCards=providerGroups.map(group=>`<article class="card"><h3><a href="${group.id}.html">${esc(termTitle(group.id))}</a></h3><p>${group.entities.length} indexed organizations with reproducible category statistics.</p></article>`).join('');
await write('docs/providers/index.html',shell('Providers Home',`<section class="prose wide"><div class="eyebrow">PROVIDER DISCOVERY</div><h1>Provider Intelligence</h1><p>Substantial provider cohorts with source coverage, CXO-role distribution, adjacent-category analysis, and canonical entity records.</p><div class="grid">${providerHubCards}</div></section>`,'Provider intelligence across the C-suite ecosystem.','Providers'));

const intelligenceCard=(item,type)=>{const href=type==='Comparison'?`compare-${item.comparison_id}.html`:`${item.id}.html`;return `<article class="card"><div class="eyebrow">${esc(type)}</div><h3><a href="${href}">${esc(item.title)}</a></h3><p>${type==='Market Map'?`${item.total_entities} canonical entities across ${item.buckets.length} documented layers.`:type==='Comparison'?`${item.entity_ids.length} organizations compared using canonical fields.`:`Coverage-aware analysis generated from dataset version ${item.dataset_version}.`}</p></article>`;};
await write('docs/intelligence/index.html',shell('Intelligence Home',`<section class="prose wide"><div class="eyebrow">DATA → INTELLIGENCE → KNOWLEDGE</div><h1>Intelligence</h1><p>Reproducible market maps, comparisons and benchmarks calculated from canonical CXO Ecosystem Index data. Unknown values remain unknown.</p><h2>Market Maps</h2><div class="grid">${intelligence.market_maps.map(item=>intelligenceCard(item,'Market Map')).join('')}</div><h2>Comparisons</h2><div class="grid">${intelligence.comparisons.map(item=>intelligenceCard(item,'Comparison')).join('')}</div><h2>Benchmarks</h2><div class="grid">${intelligence.benchmarks.filter(item=>item.id!=='data-quality').map(item=>intelligenceCard(item,'Benchmark')).join('')}</div><h2>Geographic Intelligence</h2><p><a href="silicon-valley-cxo-ecosystem.html">Silicon Valley CXO Ecosystem →</a></p><h2>Data Quality</h2><p><a href="../data-quality.html">Open the public data-quality dashboard →</a></p><h2>Machine-readable intelligence</h2><div class="download"><a href="../data/intelligence.json">Intelligence JSON</a><a href="../data/market-maps.json">Market Maps JSON</a><a href="../data/comparisons.json">Comparisons JSON</a><a href="../data/benchmarks.json">Benchmarks JSON</a></div></section>`,'Reproducible executive ecosystem intelligence generated from canonical data.','Intelligence'));

for(const map of intelligence.market_maps){
 const bucketSections=map.buckets.map(bucket=>`<section><h2>${esc(bucket.name)} <small>${bucket.count}</small></h2><div class="grid">${bucket.entity_ids.map(id=>entityCard(byId.get(id))).join('').replaceAll('href="entities/','href="../entities/')}</div></section>`).join('');
 const distribution=map.buckets.map(bucket=>`<tr><td>${esc(bucket.name)}</td><td>${bucket.count}</td><td>${Math.round(100*bucket.share)}%</td></tr>`).join('');
 const itemList=JSON.stringify({'@context':'https://schema.org','@type':'ItemList',name:map.title,numberOfItems:map.entity_ids.length,itemListElement:map.entity_ids.map((id,index)=>({'@type':'ListItem',position:index+1,url:`https://openfutureforum.github.io/cxo-ecosystem-index/entities/${byId.get(id).slug}.html`,name:byId.get(id).name}))});
 const body=`<section class="prose wide"><div class="eyebrow">MARKET MAP</div><h1>${esc(map.title)}</h1><blockquote><b>Dataset snapshot:</b> ${map.total_entities} canonical organizations across ${map.buckets.length} documented functional layers. ${map.known_count} organizations map to at least one layer; ${map.unknown_count} require more subcategory evidence.</blockquote><h2>Definition</h2><p>${esc(map.definition)}</p><div class="stats compact"><div><strong>${map.total_entities}</strong><span>Organizations</span></div><div><strong>${map.buckets.length}</strong><span>Functional layers</span></div><div><strong>${Math.round(100*map.coverage)}%</strong><span>Layer coverage</span></div></div><h2>Category distribution</h2><div class="table-wrap"><table><thead><tr><th>Layer</th><th>Count</th><th>Share of cohort</th></tr></thead><tbody>${distribution}</tbody></table></div>${bucketSections}<h2>Methodology</h2><p>Generated from canonical categories, subcategories, products, services, descriptions, and CXO-role fields in dataset ${map.dataset_version}, calculated ${map.calculated_at}. Organizations may appear in multiple layers. Missing evidence is not counted as absence.</p><h2>Download data</h2><p><a href="../data/market-maps.json">Market Maps JSON</a> · <a href="../data/cohorts/${map.id}.csv">Cohort CSV</a> · <a href="../data/cohorts/${map.id}.json">Cohort JSON</a></p><script type="application/ld+json">${itemList}</script></section>`;
 await write(`docs/intelligence/${map.id}.html`,shell(`Intelligence: ${map.id}`,body,map.definition,map.title));
}

for(const comparison of intelligence.comparisons){
 const cohort=comparison.entity_ids.map(id=>byId.get(id));const head=cohort.map(entity=>`<th><a href="../entities/${entity.slug}.html">${esc(entity.name)}</a></th>`).join('');
 const rows=comparison.dimensions.map(dimension=>`<tr><th>${esc(dimension.label)}</th>${cohort.map(entity=>{const value=dimension.values[entity.id];return `<td>${esc(Array.isArray(value)?value.join(', '):value)}</td>`;}).join('')}</tr>`).join('');
 const body=`<section class="prose wide"><div class="eyebrow">STRUCTURED COMPARISON</div><h1>${esc(comparison.title)}</h1><blockquote>Values come from canonical fields. “Not verified” means the current record lacks supporting evidence; it does not mean the capability is absent.</blockquote><div class="table-wrap"><table><thead><tr><th>Dimension</th>${head}</tr></thead><tbody>${rows}</tbody></table></div><h2>Methodology</h2><p>Generated from canonical entity records in dataset ${comparison.dataset_version} on ${comparison.generated_at}. The comparison does not rank organizations and does not infer negative claims from missing data.</p><p><a href="../data/comparisons.json">Download comparison JSON</a></p></section>`;
 await write(`docs/intelligence/compare-${comparison.comparison_id}.html`,shell(`Intelligence: compare-${comparison.comparison_id}`,body,`Structured factual comparison of ${comparison.title.toLowerCase()}.`,comparison.title));
}

for(const benchmark of intelligence.benchmarks.filter(item=>item.id!=='data-quality')){
 let content='';
 if(benchmark.metrics)content=`<div class="table-wrap"><table><thead><tr><th>Scope</th><th>Numerator</th><th>Known denominator</th><th>Unknown</th><th>Coverage</th><th>Result</th></tr></thead><tbody>${benchmark.metrics.map(metric=>`<tr><td>${esc(metric.name)}</td><td>${metric.numerator}</td><td>${metric.denominator}</td><td>${metric.unknown_count}</td><td>${Math.round(100*metric.coverage)}%</td><td>${metric.notes||`${Math.round(100*metric.value)}% of known records`}</td></tr>`).join('')}</tbody></table></div>`;
 else if(benchmark.role_distribution)content=`<div class="stats compact"><div><strong>${benchmark.exactly_one}</strong><span>Exactly one CXO role</span></div><div><strong>${benchmark.two_to_three}</strong><span>Two to three roles</span></div><div><strong>${benchmark.four_plus}</strong><span>Four or more roles</span></div></div><h2>Role distribution</h2><p>${benchmark.role_distribution.map(item=>`${esc(item.role)} ${item.count}`).join(' · ')}</p>`;
 else content=`<blockquote><b>${benchmark.status==='insufficient coverage'?'Coverage insufficient for a reliable headline benchmark.':'Usable coverage.'}</b> ${benchmark.known_count} known records and ${benchmark.unknown_count} unknown records; ${Math.round(100*benchmark.coverage)}% coverage.</blockquote>`;
 const body=`<section class="prose wide"><div class="eyebrow">DATASET BENCHMARK</div><h1>${esc(benchmark.title)}</h1>${content}<h2>Methodology</h2><p>${esc(benchmark.method||'Calculated from canonical structured fields. Unknown values are not counted as false.')}</p><p><b>Dataset:</b> ${benchmark.dataset_version} · <b>Calculated:</b> ${benchmark.calculated_at}</p><p><a href="../data/benchmarks.json">Download benchmark JSON</a></p></section>`;
 await write(`docs/intelligence/${benchmark.id}.html`,shell(`Intelligence: ${benchmark.id}`,body,`Coverage-aware ${benchmark.title.toLowerCase()} from the CXO Ecosystem Index.`,benchmark.title));
}

const siliconCategories=Object.entries(Object.groupBy(siliconValleyEntities.flatMap(entity=>entity.categories.map(category=>({category,entity}))),item=>item.category)).map(([category,items])=>[category,new Set(items.map(item=>item.entity.id)).size]).sort((a,b)=>b[1]-a[1]).slice(0,15);
const siliconRoles=Object.entries(Object.groupBy(siliconValleyEntities.flatMap(entity=>entity.cxo_roles),role=>role)).map(([role,items])=>[role,items.length]).sort((a,b)=>b[1]-a[1]);
await write('docs/intelligence/silicon-valley-cxo-ecosystem.html',shell('Intelligence: silicon-valley-cxo-ecosystem',`<section class="prose wide"><div class="eyebrow">GEOGRAPHIC INTELLIGENCE</div><h1>Silicon Valley CXO Ecosystem</h1><blockquote>The index currently identifies ${siliconValleyEntities.length} organizations with documented headquarters or operating geography in Silicon Valley, San Francisco, Palo Alto, San Jose, or the Bay Area. Headquarters and operating-market signals remain distinct in the downloadable cohort.</blockquote><div class="stats compact"><div><strong>${siliconValleyEntities.length}</strong><span>Organizations</span></div><div><strong>${new Set(siliconValleyEntities.flatMap(entity=>entity.categories)).size}</strong><span>Provider categories</span></div><div><strong>${new Set(siliconValleyEntities.flatMap(entity=>entity.cxo_roles)).size}</strong><span>CXO roles</span></div></div><h2>Provider distribution</h2><div class="table-wrap"><table><thead><tr><th>Provider category</th><th>Organizations</th></tr></thead><tbody>${siliconCategories.map(([category,count])=>`<tr><td>${esc(category)}</td><td>${count}</td></tr>`).join('')}</tbody></table></div><h2>CXO distribution</h2><p>${siliconRoles.map(([role,count])=>`${esc(role)} ${count}`).join(' · ')}</p><h2>Canonical cohort</h2><div class="grid">${siliconValleyEntities.map(entityCard).join('').replaceAll('href="entities/','href="../entities/')}</div><h2>Download cohort</h2><p><a href="../data/cohorts/silicon-valley-cxo-ecosystem.csv">CSV</a> · <a href="../data/cohorts/silicon-valley-cxo-ecosystem.json">JSON</a></p><h2>Methodology</h2><p>Generated from canonical headquarters and geography fields in dataset ${DATASET_VERSION}. Presence in this cohort does not imply headquarters unless the entity record explicitly provides it.</p></section>`,'Canonical organizations and provider distribution across the Silicon Valley CXO ecosystem.','Silicon Valley CXO Ecosystem'));

const quality=intelligence.benchmarks.find(item=>item.id==='data-quality');
const qualityHtml=shell('Data Quality',`<section class="prose wide"><div class="eyebrow">PUBLIC DATA QUALITY DASHBOARD</div><h1>Data Quality</h1><div class="stats compact"><div><strong>${quality.total_entities}</strong><span>Organizations</span></div><div><strong>${quality.total_facts}</strong><span>Sourced facts</span></div><div><strong>${sourceRegistry.length}</strong><span>Canonical sources</span></div><div><strong>${knowledgeGraph.sourced_relationship_count}</strong><span>Sourced relationships</span></div><div><strong>${knowledgeGraph.derived_reciprocal_count}</strong><span>Derived relationships</span></div><div><strong>${derivedMetricCount}</strong><span>Derived metrics</span></div></div><h2>Coverage and freshness</h2><div class="table-wrap"><table><tbody><tr><th>Verified entities</th><td>${quality.verified_entities}</td></tr><tr><th>Average sourced facts/entity</th><td>${quality.average_facts_per_entity}</td></tr><tr><th>Median sourced facts/entity</th><td>${quality.median_facts_per_entity}</td></tr><tr><th>Entities with 5+ facts</th><td>${quality.entities_with_5_plus}</td></tr><tr><th>Entities with 10+ facts</th><td>${quality.entities_with_10_plus}</td></tr><tr><th>Entities with 20+ facts</th><td>${quality.entities_with_20_plus}</td></tr><tr><th>Primary-source fact coverage</th><td>${Math.round(100*sourceMetrics.primary_fact_percentage)}%</td></tr><tr><th>Volatile facts with as-of date</th><td>${quality.volatile_facts_with_as_of_date}</td></tr><tr><th>Stale facts</th><td>${quality.stale_facts}</td></tr><tr><th>Conflicting facts</th><td>${quality.conflicting_facts}</td></tr><tr><th>Missing headquarters</th><td>${quality.missing_headquarters}</td></tr><tr><th>Missing founding year</th><td>${quality.missing_founding_year}</td></tr></tbody></table></div><h2>Fact-density distribution</h2><div class="table-wrap"><table><thead><tr><th>Facts per entity</th><th>Entities</th></tr></thead><tbody>${quality.fact_distribution.map(([label,count])=>`<tr><td>${label}</td><td>${count}</td></tr>`).join('')}</tbody></table></div><h2>Methodology</h2><p>Generated from canonical facts, sources, relationships and derived intelligence in dataset ${quality.dataset_version} on ${quality.calculated_at}. Missing values are reported rather than inferred.</p><p><a href="data/data-quality.json">Download quality JSON</a></p></section>`,'Public coverage, verification, source quality, freshness and fact-density metrics.');
await write('docs/data-quality.html',qualityHtml);

const industryGroups=Object.entries(Object.groupBy(entities.flatMap(entity=>(entity.industries||[]).map(industry=>({industry,entity}))),item=>item.industry)).map(([industry,items])=>({industry,entities:[...new Map(items.map(item=>[item.entity.id,item.entity])).values()]})).filter(group=>group.entities.length>=5).sort((a,b)=>b.entities.length-a.entities.length);
await write('docs/industries/index.html',shell('Industries Home',`<section class="prose wide"><div class="eyebrow">INDUSTRY DISCOVERY</div><h1>Industries</h1><p>Only industries with at least five canonically classified organizations receive an indexable hub.</p><div class="grid">${industryGroups.map(group=>`<article class="card"><h3><a href="${slug(group.industry)}.html">${esc(group.industry)}</a></h3><p>${group.entities.length} indexed organizations.</p></article>`).join('')}</div></section>`,'Substantial industry ecosystems generated from canonical metadata.','Industries'));
for(const group of industryGroups){const roles=[...new Set(group.entities.flatMap(entity=>entity.cxo_roles))];const categories=[...new Set(group.entities.flatMap(entity=>entity.categories))];const body=`<section class="prose wide"><div class="eyebrow">INDUSTRY ECOSYSTEM</div><h1>${esc(group.industry)}</h1><blockquote>${group.entities.length} canonical organizations, ${roles.length} CXO roles, and ${categories.length} provider categories are represented.</blockquote><h2>Provider landscape</h2><p>${categories.map(category=>esc(category)).join(' · ')}</p><div class="grid">${group.entities.map(entityCard).join('').replaceAll('href="entities/','href="../entities/')}</div><h2>Methodology</h2><p>Generated from canonical industry classifications in dataset ${DATASET_VERSION}. Office, headquarters and service geography are not inferred from industry membership.</p></section>`;await write(`docs/industries/${slug(group.industry)}.html`,shell(`Industry: ${group.industry}`,body,`Indexed providers and organizations in ${group.industry}.`,`${group.industry} Ecosystem`));}

const guideCards=cfoGuides.map(guide=>`<article class="card"><div class="eyebrow">CFO GUIDE</div><h3><a href="guides/${guide.slug}.html">${esc(guide.title)}</a></h3><p>${esc(guide.summary)}</p><small>Updated ${esc(guide.updated)}</small></article>`).join('');
await write('docs/cfo-guides.html',shell('CFO Guides',`<section class="prose wide"><div class="eyebrow">ORIGINAL DECISION RESOURCES</div><h1>CFO guides</h1><p>Evidence-backed, vendor-neutral resources generated from structured source records.</p><div class="grid">${guideCards}</div></section>`,'Evidence-backed, vendor-neutral decision resources for CFOs.'));
for(const guide of cfoGuides){
 const sections=guide.sections.map(section=>`<section><h2>${esc(section.heading)}</h2><p>${esc(section.content)}</p>${section.bullets?`<ul>${section.bullets.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`:''}</section>`).join('');
 const sources=guide.sources.map(source=>`<li><a href="${esc(source.url)}">${esc(source.title)}</a><span>${esc(source.publisher)}</span></li>`).join('');
 const articleLd=JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:guide.title,description:guide.summary,dateModified:guide.updated,author:{'@type':'Organization',name:'Open Future Forum'},publisher:{'@type':'Organization',name:'Open Future Forum'},mainEntityOfPage:`https://openfutureforum.github.io/cxo-ecosystem-index/guides/${guide.slug}.html`});
 await write(`docs/guides/${guide.slug}.html`,shell(`Guide: ${guide.title}`,`<article class="prose"><div class="eyebrow">CFO DECISION RESOURCE</div><h1>${esc(guide.title)}</h1><p>${esc(guide.summary)}</p><p><b>Audience:</b> ${esc(guide.audience.join(', '))} · <b>Updated:</b> ${esc(guide.updated)}</p>${sections}<h2>Primary sources</h2><ul class="sources">${sources}</ul><p><small>This guide is educational and does not replace accounting, legal, security, or audit advice.</small></p><script type="application/ld+json">${articleLd}</script></article>`,guide.summary));
}

const taxonomySection=(heading,items)=>`<section><h2>${heading}</h2><div class="table-wrap"><table><thead><tr><th>Stable ID</th><th>Term</th><th>Neutral definition</th></tr></thead><tbody>${items.map(item=>`<tr><td><code>${esc(item.id)}</code></td><td>${esc(item.label)}</td><td>${esc(item.definition)}</td></tr>`).join('')}</tbody></table></div></section>`;
const entityAnswerList=items=>items.length?`<ul>${items.map(entity=>`<li><a href="entities/${entity.slug}.html">${esc(entity.name)}</a></li>`).join('')}</ul>`:'<p>No evidence-backed organization is currently classified for this query.</p>';
const executiveCommunityDefinition=semantic.community_formats.find(item=>item.id==='executive-community').definition;
const cisoEventOrganizations=entities.filter(entity=>entity.cxo_roles.includes('CISO')&&entity.event_formats.length);
const benchmarkPublishers=entities.filter(entity=>entity.intelligence_types.includes('benchmark'));
const operatingPartnerOrganizations=entities.filter(entity=>entity.audiences.includes('operating-partners'));
const cmoNetworkOrganizations=entities.filter(entity=>entity.cxo_roles.includes('CMO')&&entity.community_formats.length);
const executiveResearchPublishers=entities.filter(entity=>entity.intelligence_types.includes('executive-research'));
const aliasRows=taxonomyAliases.aliases.map(item=>`<tr><td>${esc(item.alias)}</td><td>${esc(item.dimension.replaceAll('_',' '))}</td><td><code>${esc(item.canonical_id)}</code></td></tr>`).join('');
const mappingCards=roleMappings.mappings.map(mapping=>`<article class="card"><h3>${esc(mapping.label)}</h3><p>${mapping.community_format_ids.length} community formats · ${mapping.event_format_ids.length} event formats · ${mapping.intelligence_type_ids.length} intelligence types · ${mapping.executive_need_ids.length} needs · ${mapping.topic_ids.length} topics.</p></article>`).join('');
const faqLd=JSON.stringify({'@context':'https://schema.org','@type':'FAQPage',mainEntity:[['What is an executive community?',executiveCommunityDefinition],['What organizations serve CFOs?',`${cfoEntities.length} canonical organizations are classified as serving CFOs in dataset ${DATASET_VERSION}.`],['Which organizations run CISO events?',`${cisoEventOrganizations.length} organizations have both a CISO role association and at least one evidence-backed event format.`],['Which organizations publish executive benchmarks?',`${benchmarkPublishers.length} organizations have an evidence-backed benchmark classification.`],['Which organizations serve private equity operating partners?',`${operatingPartnerOrganizations.length} organizations have an evidence-backed operating-partner audience classification.`],['Which organizations provide CMO networks?',`${cmoNetworkOrganizations.length} organizations have both a CMO role association and an evidence-backed community format.`],['What types of executive events exist?',`${semantic.event_formats.length} controlled event-format terms are defined in dataset ${DATASET_VERSION}.`],['Which organizations provide executive research?',`${executiveResearchPublishers.length} organizations have an evidence-backed executive-research classification.`]].map(([name,text])=>({'@type':'Question',name,acceptedAnswer:{'@type':'Answer',text}}))});
const taxonomyBody=`<section class="prose wide"><div class="eyebrow">CONTROLLED KNOWLEDGE MODEL</div><h1>CXO formats, intelligence and outcomes taxonomy</h1><p>The Index maps organizations across executive roles, provider types, ongoing community formats, time-bounded event formats, research and intelligence, decision resources, executive needs, topics, audiences, industries, and geographies.</p><blockquote>Role and audience mappings identify relevant controlled vocabulary. They do not assert that every organization in a cohort offers every mapped format, resource, or outcome.</blockquote><h2>Role and audience mappings</h2><div class="grid">${mappingCards}</div><h2>Questions this dataset can answer</h2><h3>What is an executive community?</h3><p>${esc(executiveCommunityDefinition)}</p><h3>What organizations serve CFOs?</h3><p><a href="cfo-ecosystem.html">${cfoEntities.length} canonical organizations are classified as serving CFOs.</a></p><h3>Which organizations run CISO events?</h3>${entityAnswerList(cisoEventOrganizations)}<h3>Which organizations publish executive benchmarks?</h3>${entityAnswerList(benchmarkPublishers)}<h3>Which organizations serve private equity operating partners?</h3>${entityAnswerList(operatingPartnerOrganizations)}<h3>Which organizations provide CMO networks?</h3>${entityAnswerList(cmoNetworkOrganizations)}<h3>What types of executive events exist?</h3><p>${semantic.event_formats.map(item=>esc(item.label)).join(' · ')}</p><h3>Which organizations provide executive research?</h3>${entityAnswerList(executiveResearchPublishers)}${taxonomySection('Community and membership formats',semantic.community_formats)}${taxonomySection('Event formats',semantic.event_formats)}${taxonomySection('Research and intelligence',semantic.intelligence_types)}${taxonomySection('Frameworks and decision resources',semantic.resource_types)}${taxonomySection('Executive needs and outcomes',semantic.executive_needs)}${taxonomySection('Executive priorities and topics',semantic.topics)}${taxonomySection('Additional audiences',semantic.audiences)}<section><h2>Canonical aliases</h2><p>Near-synonyms resolve to one term rather than creating duplicate categories.</p><div class="table-wrap"><table><thead><tr><th>Alias</th><th>Dimension</th><th>Canonical ID</th></tr></thead><tbody>${aliasRows}</tbody></table></div></section><h2>Machine-readable files</h2><div class="download"><a href="data/taxonomy.json">Taxonomy JSON</a><a href="data/taxonomy-aliases.json">Alias JSON</a><a href="data/role-mappings.json">Role mappings JSON</a><a href="data/semantic-relationships.json">Semantic relationships JSON</a></div><script type="application/ld+json">${faqLd}</script></section>`;
await write('docs/taxonomy.html',shell('Taxonomy',taxonomyBody,'Controlled definitions, role mappings and evidence-backed answers for CXO formats, intelligence, needs, topics and audiences.','Taxonomy'));

await write('docs/methodology.html',shell('Methodology',`<section class="prose"><div class="eyebrow">TRUST AND GOVERNANCE</div><h1>Methodology</h1><h2>Classification model</h2><p>Organizations are classified independently across executive roles, provider types, community formats, event formats, intelligence types, resources, executive needs, topics, audiences, and geographies. A multi-category organization retains one canonical entity record.</p><h2>Controlled vocabulary</h2><p>Every semantic term has a stable ID and neutral definition. Closely related phrases resolve through the alias registry to one canonical concept unless they represent a material functional distinction. Community formats describe ongoing structures; event formats describe time-bounded gatherings; first-party research remains distinct from editorial commentary.</p><p><a href="taxonomy.html">Review the controlled taxonomy, aliases and role mappings.</a></p><h2>Evidence requirement</h2><p>Entity associations require reasonable evidence from official organization, event, research, regulatory, government, or reputable third-party sources. A passing keyword mention is insufficient. Semantic relationship exports retain the evidence URLs used for each classified field.</p><h2>Multi-category organizations</h2><p>An organization may serve multiple roles or appear in multiple dimensions without creating duplicate entity records. Missing associations remain unknown and are not inferred from a company name or isolated article mention.</p><h2>Indexability gate</h2><p>Arbitrary filter combinations remain application state. A canonical page is created only when it has stable intent, enough substantive entities, distinct analysis, and durable value. Dataset v${DATASET_VERSION} adds one substantive taxonomy authority page; it does not create role-format-topic combination pages.</p><h2>Commercial neutrality</h2><p>Inclusion does not constitute endorsement. Commercial relationships do not influence inclusion, ranking, scoring, descriptions, or category placement.</p><h2>Versioning and updates</h2><p>Schema and dataset versions are published in exports. Stable IDs do not change without a documented migration. Taxonomy additions and aliases are recorded in the taxonomy changelog; breaking entity-schema changes require a schema-version update.</p></section>`));
const added=expansion.entities.filter(item=>item.status==='added');const unresolved=expansion.entities.filter(item=>item.status==='unresolved');
const reportRows=items=>items.map(item=>`<tr><td>${esc(item.name)}</td><td>${esc(item.priority||'')}</td><td>${esc(item.status)}</td><td>${esc(item.reason||item.relationship_notes||'Verified from the official organization website.')}</td></tr>`).join('');
await write('docs/reconciliation-report.html',shell('Expansion Reconciliation Report',`<section class="prose wide"><div class="eyebrow">DATASET EXPANSION AUDIT</div><h1>Organization reconciliation report</h1><p>Every supplied organization or alias was assigned a visible state. Priority indicates editorial research order, not rank, quality, sponsorship, or endorsement.</p><div class="stats compact"><div><strong>51</strong><span>Organizations before</span></div><div><strong>${entities.length}</strong><span>Organizations after</span></div><div><strong>${added.length}</strong><span>New canonical entities</span></div></div><h2>Duplicates and aliases resolved</h2><ul>${expansion.duplicate_aliases.map(item=>`<li><b>${esc(item.supplied)}</b> → ${esc(item.canonical)}</li>`).join('')}</ul><h2>Added</h2><div class="table-wrap"><table><thead><tr><th>Organization</th><th>Priority</th><th>Status</th><th>Resolution</th></tr></thead><tbody>${reportRows(added)}</tbody></table></div><h2>Unresolved</h2><p>These names remain in the research queue because assigning a canonical entity without further evidence would risk a false match.</p><div class="table-wrap"><table><thead><tr><th>Supplied name</th><th>Priority</th><th>Status</th><th>Reason</th></tr></thead><tbody>${reportRows(unresolved)}</tbody></table></div><h2>Validation statement</h2><p><b>Every name supplied in the expansion brief has been accounted for</b> as an added canonical entity, merged alias, repeated multi-category reference, or unresolved research item. No name was silently omitted.</p></section>`,'Audit trail for the August 2026 CXO Ecosystem Index organization expansion.'));
const resolutionRows=resolutionV050.map(item=>`<tr><td>${esc(item.original)}</td><td>${esc(item.canonical)}</td><td><a href="https://${esc(item.domain)}">${esc(item.domain)}</a></td><td>${esc(item.result)}</td><td>${esc(item.category)}</td><td>${esc(item.confidence)}</td></tr>`).join('');
await write('docs/v050-report.html',shell('v050 Report',`<section class="prose wide"><div class="eyebrow">RELEASE AUDIT</div><h1>v0.5.0 Fact Depth & Entity Resolution</h1><div class="stats compact"><div><strong>175</strong><span>Organizations before</span></div><div><strong>${entities.length}</strong><span>Organizations after</span></div><div><strong>${s.sourced_facts}</strong><span>Sourced facts</span></div><div><strong>${s.facts_per_entity}</strong><span>Facts per entity</span></div><div><strong>${s.primary_source_coverage}%</strong><span>Primary-source coverage</span></div></div><h2>Former unresolved entities</h2><p>All 18 former unresolved names now have an explicit canonical resolution. Claims are limited to what the cited official source supports.</p><div class="table-wrap"><table><thead><tr><th>Original</th><th>Canonical entity</th><th>Domain</th><th>Resolution</th><th>Category</th><th>Confidence</th></tr></thead><tbody>${resolutionRows}</tbody></table></div><h2>Fact methodology</h2><p>A sourced fact is one explicit field/value assertion connected to at least one source ID and a last-verified date. Array values such as executive roles and provider categories count individually because each is independently queryable. Missing values are omitted. Volatile values require an as-of date and are not inferred.</p></section>`,'v0.5.0 release report covering fact depth and resolution of 18 former unresolved organizations.','v0.5.0 Fact Depth Report'));
const downloadDistributions=[['Entities JSON','application/json','entities.json'],['Entities CSV','text/csv','entities.csv'],['Facts JSON','application/json','facts.json'],['Sources JSON','application/json','sources.json'],['Organization Relationships JSON','application/json','relationships.json'],['Semantic Relationships JSON','application/json','semantic-relationships.json'],['Semantic Relationship Schema','application/schema+json','semantic-relationship.schema.json'],['Knowledge Graph JSON','application/json','knowledge-graph.json'],['Search Index JSON','application/json',searchIndexFile],['Taxonomy JSON','application/json','taxonomy.json'],['Taxonomy Aliases JSON','application/json','taxonomy-aliases.json'],['Role Mappings JSON','application/json','role-mappings.json'],['Definitions JSON','application/json','definitions.json'],['Intelligence JSON','application/json','intelligence.json'],['Benchmarks JSON','application/json','benchmarks.json'],['Market Maps JSON','application/json','market-maps.json'],['Comparisons JSON','application/json','comparisons.json'],['Build Manifest JSON','application/json','build-manifest.json'],['Current Release Manifest JSON','application/json','latest.json']];
const cohortIds=[...intelligence.market_maps.map(item=>item.id),'silicon-valley-cxo-ecosystem'];
const cohortDistributions=cohortIds.flatMap(id=>[[`${termTitle(id)} cohort CSV`,'text/csv',`cohorts/${id}.csv`],[`${termTitle(id)} cohort JSON`,'application/json',`cohorts/${id}.json`]]);
const allDistributions=[...downloadDistributions,...cohortDistributions];
const catalogUrl='https://openfutureforum.github.io/cxo-ecosystem-index/data.html';
const datasetLd=JSON.stringify({'@context':'https://schema.org','@graph':[{'@type':'DataCatalog','@id':`${catalogUrl}#catalog`,name:'CXO Ecosystem Index Data Catalog',url:catalogUrl,datePublished:'2026-08-11',dateModified:CALCULATED_AT,publisher:{'@type':'Organization',name:'Open Future Forum'},dataset:{'@id':`${catalogUrl}#dataset`}},{'@type':'Dataset','@id':`${catalogUrl}#dataset`,identifier:'https://openfutureforum.github.io/cxo-ecosystem-index/',name:'CXO Ecosystem Index',description:'Open-source structured intelligence on organizations serving executive functions.',url:catalogUrl,version:DATASET_VERSION,datePublished:'2026-08-11',dateModified:CALCULATED_AT,creator:{'@type':'Organization',name:'Open Future Forum'},publisher:{'@type':'Organization',name:'Open Future Forum'},license:'https://opensource.org/license/mit/',keywords:['C-suite','CXO','executive ecosystems','business intelligence','knowledge graph','open data'],spatialCoverage:'Global representative coverage; comprehensive global coverage is not claimed.',includedInDataCatalog:{'@id':`${catalogUrl}#catalog`},sameAs:'https://github.com/OpenFutureForum/cxo-ecosystem-index',isBasedOn:'https://openfutureforum.github.io/cxo-ecosystem-index/methodology.html',distribution:allDistributions.map(([name,encodingFormat,file])=>({'@type':'DataDownload',name,encodingFormat,contentUrl:`https://openfutureforum.github.io/cxo-ecosystem-index/data/${file}`}))}]});
const downloadLinks=downloadDistributions.map(([label,,file])=>`<a href="data/${file}">${label}</a>`).join('');
const cohortLinks=cohortDistributions.map(([label,,file])=>`<a href="data/${file}">${label}</a>`).join('');
await write('docs/data.html',shell('Data',`<section class="prose wide"><div class="eyebrow">OPEN DATA AUTHORITY HUB</div><h1>CXO Ecosystem Index data</h1><p>Canonical and derived exports are rebuilt from validated source records for every release.</p><div class="stats compact"><div><strong>${s.entities}</strong><span>Organizations</span></div><div><strong>${s.sourced_facts}</strong><span>Sourced facts</span></div><div><strong>${sourceRegistry.length}</strong><span>Canonical sources</span></div><div><strong>${knowledgeGraph.sourced_relationship_count}</strong><span>Organization relationships</span></div><div><strong>${semanticRelationships.length}</strong><span>Semantic relationships</span></div><div><strong>${derivedMetricCount}</strong><span>Derived metrics</span></div></div><h2>Current release</h2><dl><dt>Dataset version</dt><dd>${DATASET_VERSION}</dd><dt>Entity schema version</dt><dd>${SCHEMA_VERSION}</dd><dt>Derived intelligence schema</dt><dd>1.2.0</dd><dt>Last dataset update</dt><dd>${CALCULATED_AT}</dd><dt>Build commit</dt><dd><code>${buildCommit}</code></dd><dt>Release fingerprint</dt><dd><code>${releaseFingerprint}</code></dd><dt>Creator and publisher</dt><dd>Open Future Forum</dd><dt>License</dt><dd>MIT</dd><dt>Coverage</dt><dd>Representative dataset; comprehensive global coverage is not claimed.</dd></dl><p><a href="data/latest.json">Current Release Manifest</a> is provided for programmatic version discovery, debugging, provenance and external data consumers. It is not a search-engine recrawl mechanism.</p><h2>Downloads</h2><div class="download">${downloadLinks}</div><h2>Analytical cohort downloads</h2><div class="download">${cohortLinks}</div><h2>Methods, quality and citation</h2><div class="download"><a href="taxonomy.html">Controlled taxonomy</a><a href="methodology.html">Methodology</a><a href="data-quality.html">Data quality dashboard</a><a href="intelligence/">Intelligence</a><a href="CITATION.cff">Citation metadata</a><a href="reports/search-console-handoff.json">Search Console handoff</a><a href="https://github.com/OpenFutureForum/cxo-ecosystem-index">Repository</a></div><h2>Fact and relationship model</h2><p>Each source-linked fact records a field, value, source ID, and verification or as-of date. Organization-to-organization relationships remain distinct from evidence-linked semantic relationships such as <code>serves_role</code>, <code>offers_event_format</code>, <code>publishes_intelligence</code>, and <code>addresses_topic</code>. Derived reciprocal edges and metrics are explicitly marked.</p><h2>Historical implementation reports</h2><p><a href="reconciliation-report.html">Expansion reconciliation report</a> · <a href="v050-report.html">v0.5 fact-depth report</a></p><script type="application/ld+json">${datasetLd}</script></section>`,'Download the current CXO Ecosystem Index entities, facts, sources, relationships, knowledge graph, taxonomy, search index and intelligence datasets.','Data'));

const urls=['','cxo-ecosystems.html','cfo-ecosystem.html',...rolePages.map(group=>`${slug(group.label)}-ecosystem.html`),'providers/','intelligence/','industries/','data-quality.html','intelligence/silicon-valley-cxo-ecosystem.html','cfo-guides.html',...cfoGuides.map(g=>`guides/${g.slug}.html`),...providerGroups.map(group=>`providers/${group.id}.html`),...formatGroups.map(group=>`formats/${group.id}.html`),...intelligence.market_maps.map(item=>`intelligence/${item.id}.html`),...intelligence.comparisons.map(item=>`intelligence/compare-${item.comparison_id}.html`),...intelligence.benchmarks.filter(item=>item.id!=='data-quality').map(item=>`intelligence/${item.id}.html`),...industryGroups.map(group=>`industries/${slug(group.industry)}.html`),'reconciliation-report.html','v050-report.html','taxonomy.html','methodology.html','data.html',...entities.map(e=>`entities/${e.slug}.html`)];
const maxDate=values=>values.filter(value=>/^\d{4}-\d{2}-\d{2}$/.test(value||'')).sort().at(-1)||null;
const entityModified=entity=>maxDate([entity?.last_verified,...(entity?.facts||[]).flatMap(fact=>[fact.last_verified,fact.as_of])]);
const cohortModified=members=>maxDate(members.map(entityModified));
const datasetLastmod=cohortModified(entities);
const lastmodFor=url=>{
 if(url.startsWith('entities/'))return entityModified(entities.find(item=>`${item.slug}.html`===url.slice(9)));
 if(url.startsWith('guides/'))return cfoGuides.find(guide=>`${guide.slug}.html`===url.slice(7))?.updated||null;
 if(['methodology.html','reconciliation-report.html','v050-report.html'].includes(url))return null;
 if(url==='cfo-guides.html')return maxDate(cfoGuides.map(guide=>guide.updated));
 if(url==='intelligence/silicon-valley-cxo-ecosystem.html')return cohortModified(siliconValleyEntities);
 if(url.startsWith('providers/')&&url!=='providers/'){const id=url.slice(10,-5);return cohortModified(providerGroups.find(group=>group.id===id)?.entities||[]);}
 if(url.startsWith('formats/')){const id=url.slice(8,-5);return cohortModified(formatGroups.find(group=>group.id===id)?.entities||[]);}
 if(url.startsWith('industries/')&&url!=='industries/'){const id=url.slice(11,-5);return cohortModified(industryGroups.find(group=>slug(group.industry)===id)?.entities||[]);}
 if(url.startsWith('intelligence/')){const id=url.slice(13,-5);const map=intelligence.market_maps.find(item=>item.id===id);if(map)return cohortModified(map.entity_ids.map(entityId=>byId.get(entityId)));const comparison=intelligence.comparisons.find(item=>`compare-${item.comparison_id}`===id);if(comparison)return cohortModified(comparison.entity_ids.map(entityId=>byId.get(entityId)));return datasetLastmod;}
 if(url==='cfo-ecosystem.html')return cohortModified(cfoEntities);
 const role=rolePages.find(group=>`${slug(group.label)}-ecosystem.html`===url);if(role)return cohortModified(entities.filter(entity=>role.roles.some(item=>entity.cxo_roles.includes(item))));
 return datasetLastmod;
};
await write('docs/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url=>{const lastmod=lastmodFor(url);return `  <url><loc>https://openfutureforum.github.io/cxo-ecosystem-index/${url}</loc>${lastmod?`<lastmod>${lastmod}</lastmod>`:''}</url>`;}).join('\n')}\n</urlset>\n`);
const priorityUrls=['','data.html','data-quality.html','cxo-ecosystems.html','cfo-ecosystem.html','ciso-ecosystem.html','cio-cto-ecosystem.html','providers/cfo-technology.html','providers/ai-security.html','intelligence/','intelligence/cfo-technology.html','intelligence/ai-security.html','intelligence/compare-cfo-spend-platforms.html','intelligence/ai-capability.html','taxonomy.html','methodology.html'].map(url=>`https://openfutureforum.github.io/cxo-ecosystem-index/${url}`);
await write('docs/reports/search-console-handoff.json',JSON.stringify({release:releaseLabel,release_fingerprint:releaseFingerprint,generated_at:s.generated_at,submission_status:'not submitted',note:'Candidate URLs for a manual Search Console handoff. This build does not ping or claim submission to any search engine.',sitemap_url:'https://openfutureforum.github.io/cxo-ecosystem-index/sitemap.xml',priority_urls:priorityUrls},null,2)+'\n');
await write('docs/robots.txt','User-agent: *\nAllow: /\nSitemap: https://openfutureforum.github.io/cxo-ecosystem-index/sitemap.xml\n');
await write('docs/llms.txt',`# CXO Ecosystem Index\n\nIndependent structured index maintained by Open Future Forum. Inclusion does not imply endorsement.\n\nRelease: ${releaseLabel}\nEntity schema: ${SCHEMA_VERSION}\nLast dataset update: ${CALCULATED_AT}\nRelease fingerprint: ${releaseFingerprint}\n\nThe Index maps:\n- CXO roles and additional executive or investment audiences\n- organizations and provider types\n- ongoing communities, networks and membership formats\n- time-bounded event formats\n- research, benchmarks and other intelligence types\n- frameworks and decision resources\n- executive needs and outcomes\n- leadership priorities and topics\n- industries and geographies\n\nClassification policy:\n- every entity association requires evidence\n- missing values remain unknown\n- community formats are distinct from event formats\n- first-party research is distinct from editorial commentary\n- arbitrary role/format/topic combinations remain filters, not indexable pages\n\nCanonical resources:\n- Homepage: https://openfutureforum.github.io/cxo-ecosystem-index/\n- Taxonomy and AEO answers: https://openfutureforum.github.io/cxo-ecosystem-index/taxonomy.html\n- Data authority hub: https://openfutureforum.github.io/cxo-ecosystem-index/data.html\n- Methodology: https://openfutureforum.github.io/cxo-ecosystem-index/methodology.html\n- Intelligence: https://openfutureforum.github.io/cxo-ecosystem-index/intelligence/\n- Build manifest: https://openfutureforum.github.io/cxo-ecosystem-index/data/build-manifest.json\n- Current Release Manifest: https://openfutureforum.github.io/cxo-ecosystem-index/data/latest.json\n- Entities: https://openfutureforum.github.io/cxo-ecosystem-index/data/entities.json\n- Facts: https://openfutureforum.github.io/cxo-ecosystem-index/data/facts.json\n- Sources: https://openfutureforum.github.io/cxo-ecosystem-index/data/sources.json\n- Organization relationships: https://openfutureforum.github.io/cxo-ecosystem-index/data/relationships.json\n- Semantic relationships: https://openfutureforum.github.io/cxo-ecosystem-index/data/semantic-relationships.json\n- Knowledge graph: https://openfutureforum.github.io/cxo-ecosystem-index/data/knowledge-graph.json\n- Taxonomy: https://openfutureforum.github.io/cxo-ecosystem-index/data/taxonomy.json\n- Taxonomy aliases: https://openfutureforum.github.io/cxo-ecosystem-index/data/taxonomy-aliases.json\n- Role mappings: https://openfutureforum.github.io/cxo-ecosystem-index/data/role-mappings.json\n- Fingerprinted search index: https://openfutureforum.github.io/cxo-ecosystem-index/data/${searchIndexFile}\n- Citation: https://openfutureforum.github.io/cxo-ecosystem-index/CITATION.cff\n- Repository: https://github.com/OpenFutureForum/cxo-ecosystem-index\n`);
const testFiles=await fs.readdir(path.join(root,'tests'));let testCount=0;for(const file of testFiles.filter(file=>file.endsWith('.test.mjs'))){const source=await fs.readFile(path.join(root,'tests',file),'utf8');testCount+=(source.match(/^test\s*\(/gm)||[]).length;}
const readmePath=path.join(root,'README.md');const readme=await fs.readFile(readmePath,'utf8');const statusBlock=`<!-- DATASET_STATUS_START -->\n## Current dataset\n\n| Measure | Current value |\n|---|---:|\n| Release | ${DATASET_VERSION} |\n| Entity schema | ${SCHEMA_VERSION} |\n| Canonical organizations | ${s.entities.toLocaleString('en-US')} |\n| Sourced facts | ${s.sourced_facts.toLocaleString('en-US')} |\n| Canonical sources | ${sourceRegistry.length.toLocaleString('en-US')} |\n| Sourced relationships | ${knowledgeGraph.sourced_relationship_count} |\n| Derived reciprocal relationships | ${knowledgeGraph.derived_reciprocal_count} |\n| Derived metrics | ${derivedMetricCount} |\n| Tests | ${testCount} |\n<!-- DATASET_STATUS_END -->`;await fs.writeFile(readmePath,readme.replace(/<!-- DATASET_STATUS_START -->[\s\S]*?<!-- DATASET_STATUS_END -->/,statusBlock));
console.log(`Built ${entities.length} entity pages for dataset ${DATASET_VERSION} with commit metadata ${buildCommit.slice(0,12)}.`);
