import fs from 'node:fs/promises';
import path from 'node:path';
import {load,readJSON,write,stats,esc,slug,root} from './lib.mjs';

const {entities,taxonomy,semantic,definitions}=await load();
const cfoTaxonomy=await readJSON('data/taxonomy/cfo.json');
const cfoGuides=await readJSON('data/guides/cfo.json');
const expansion=await readJSON('data/expansions/2026-08-supplied.json');
const resolutionV050=await readJSON('data/reconciliation-v050.json');
const s=stats(entities);
for(const folder of ['entities','providers','formats'])await fs.rm(path.join(root,'docs',folder),{recursive:true,force:true});
const dimensions=['provider_types','community_formats','event_formats','intelligence_types','resource_types','executive_needs','topics','audiences'];
const vocab=new Map(Object.entries(semantic).flatMap(([dimension,items])=>items.map(item=>[`${dimension}:${item.id}`,item])));
const labels=(dimension,ids=[])=>ids.map(id=>vocab.get(`${dimension}:${id}`)?.label||id);
const q=value=>`"${String(value??'').replaceAll('"','""')}"`;
const cols=['id','name','slug','entity_type','website','cxo_roles','categories',...dimensions,'industries','geographies','verification_status','last_verified'];
const csv=[cols.join(','),...entities.map(entity=>cols.map(key=>q(Array.isArray(entity[key])?entity[key].join('|'):entity[key])).join(','))].join('\n')+'\n';

await write('data/exports/entities.json',JSON.stringify({schema_version:'2.2.0',dataset_version:'0.5.0',generated_at:s.generated_at,dimensions,entities},null,2)+'\n');
await write('data/exports/entities.csv',csv);
await write('docs/data/entities.json',JSON.stringify(entities));
await write('docs/data/statistics.json',JSON.stringify(s,null,2));
await write('docs/data/definitions.json',JSON.stringify(definitions,null,2));
await write('docs/data/taxonomy.json',JSON.stringify(semantic,null,2));
await write('docs/data/entities.csv',csv);

const depth=title=>/^(Entity:|Guide:|Provider:|Format:)/.test(title)?'../':'';
const canonicalPath=title=>title==='Home'?'':title.startsWith('Entity:')?`entities/${slug(title.slice(7))}.html`:title.startsWith('Guide:')?`guides/${slug(title.slice(6))}.html`:title.startsWith('Provider:')?`providers/${slug(title.slice(9))}.html`:title.startsWith('Format:')?`formats/${slug(title.slice(7))}.html`:`${slug(title)}.html`;
const shell=(title,body,description='Open-source intelligence for the C-suite.',pageTitle=title)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(pageTitle)} | CXO Ecosystem Index</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="https://openfutureforum.github.io/cxo-ecosystem-index/${canonicalPath(title)}"><meta property="og:title" content="${esc(pageTitle)} | CXO Ecosystem Index"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><link rel="stylesheet" href="${depth(title)}assets/style.css"></head><body><header><a class="brand" href="${depth(title)}index.html"><b>CXO</b> Ecosystem Index</a><nav><a href="${depth(title)}index.html#explore">Explore</a><a href="${depth(title)}cfo-ecosystem.html">CFO</a><a href="${depth(title)}cxo-ecosystems.html">CXO Ecosystems</a><a href="${depth(title)}methodology.html">Methodology</a><a href="${depth(title)}data.html">Data</a><a href="https://github.com/OpenFutureForum/cxo-ecosystem-index">GitHub</a></nav></header><main>${body}</main><footer><p>Independent structured index maintained by Open Future Forum. Inclusion does not imply endorsement.</p><p><a href="https://openfutureforum.github.io/executive-communities-index/">Executive Communities Index</a> · <a href="https://openfutureforum.github.io/executive-community-playbook/">Executive Community Playbook</a></p></footer></body></html>`;

const entityCard=entity=>`<article class="card" data-name="${esc(entity.name.toLowerCase())}" data-cxo="${esc(entity.cxo_roles.join('|'))}" data-provider="${esc(entity.provider_types.join('|'))}" data-format="${esc([...entity.community_formats,...entity.event_formats].join('|'))}" data-topic="${esc(entity.topics.join('|'))}" data-need="${esc(entity.executive_needs.join('|'))}" data-geo="${esc(entity.geographies.join('|'))}"><div class="eyebrow">${esc(entity.entity_type)}</div><h3><a href="entities/${entity.slug}.html">${esc(entity.name)}</a></h3><p>${esc(entity.description)}</p><div class="tags">${entity.cxo_roles.slice(0,4).map(x=>`<span>${esc(x)}</span>`).join('')}</div><small>${esc(entity.categories.join(' · '))}</small></article>`;
const entityCards=entities.map(entityCard).join('');
const statCards=Object.entries({Organizations:s.entities,'Sourced facts':s.sourced_facts,'Verified entities':s.verified_entities,'CXO functions':s.cxo_functions,'Provider categories':s.provider_categories,'Geographic markets':s.geographies}).map(([key,value])=>`<div><strong>${value}</strong><span>${key}</span></div>`).join('');
const select=(label,id,options)=>`<label>${label}<select id="${id}"><option value="">All</option>${options.map(x=>`<option value="${esc(typeof x==='string'?x:x.id)}">${esc(typeof x==='string'?x:x.label)}</option>`).join('')}</select></label>`;

const groupByTerm=(field,minimum)=>Object.entries(Object.groupBy(entities.flatMap(entity=>entity[field].map(id=>({id,entity}))),item=>item.id)).map(([id,items])=>({id,entities:items.map(item=>item.entity)})).filter(group=>group.entities.length>=minimum).sort((a,b)=>b.entities.length-a.entities.length||a.id.localeCompare(b.id));
const providerGroups=groupByTerm('provider_types',4);
const formatGroups=groupByTerm('community_formats',3);
const termTitle=id=>id.split('-').map(word=>({ai:'AI',cfo:'CFO',hr:'HR',m:'M'}[word]||word[0].toUpperCase()+word.slice(1))).join(' ').replace('M A','M&A');
const browseLinks=[...providerGroups.map(group=>`<a href="providers/${group.id}.html">${esc(termTitle(group.id))} <small>${group.entities.length}</small></a>`),...formatGroups.map(group=>`<a href="formats/${group.id}.html">${esc(vocab.get(`community_formats:${group.id}`)?.label||termTitle(group.id))} <small>${group.entities.length}</small></a>`)].join('');

const home=`<section class="hero"><div class="eyebrow">OPEN-SOURCE C-SUITE INTELLIGENCE</div><h1>CXO Ecosystem Index</h1><p>Structured intelligence on who serves executives, which formats they offer, what intelligence they publish, which needs they address, and where they operate.</p><div class="actions"><a href="#explore">Explore the index</a><a class="secondary" href="data.html">Download data</a></div></section><section class="stats">${statCards}</section><section id="explore"><div class="section-head"><div><div class="eyebrow">CANONICAL ENTITY INDEX</div><h2>Explore the ecosystem</h2></div><p>Filter one canonical dataset. Filter combinations are application state, not automatically generated SEO pages.</p></div><div class="filters expanded"><label>Search<input id="search" type="search" placeholder="Name, type, format, topic, or need"></label>${select('CXO role','cxo',taxonomy.cxo_roles)}${select('Provider type','provider',taxonomy.categories.map(x=>({id:slug(x),label:x})))}${select('Format','format',[...semantic.community_formats,...semantic.event_formats])}${select('Topic','topic',semantic.topics)}${select('Executive need','need',semantic.executive_needs)}${select('Geography','geo',taxonomy.geographies)}</div><p id="result-count" class="count"></p><div id="grid" class="grid">${entityCards}</div></section><section class="principles"><div><div class="eyebrow">CONTROLLED MODEL</div><h2>Explicit relationships, visible evidence.</h2></div><ol><li><b>Canonical records</b><span>One entity can serve multiple roles, formats, topics, and needs without duplicate pages.</span></li><li><b>Controlled terms</b><span>Stable IDs and neutral definitions prevent synonym drift.</span></li><li><b>Evidence</b><span>Entity associations require official or reputable support.</span></li></ol></section><script src="assets/app.js"></script>`;
const homeWithBrowse=home.replace('<section id="explore">',`<section class="prose wide"><div class="eyebrow">CURATED BROWSE PAGES</div><h2>Browse established ecosystem categories</h2><p>These pages pass the indexability gate: each represents stable intent and at least three evidence-backed organizations. More specific combinations remain filters.</p><p><a href="reconciliation-report.html">Read the latest organization reconciliation report →</a></p><div class="download">${browseLinks}</div></section><section id="explore">`);
await write('docs/index.html',shell('Home',homeWithBrowse));

for(const entity of entities){
 const facts=[['Organization type',entity.entity_type],['Common names / aliases',(entity.aliases||[]).join(', ')],['Parent company',entity.parent_company],['Relationship notes',entity.relationship_notes],['Editorial research priority',entity.editorial_priority],['Serves',entity.cxo_roles.join(', ')],['Provider categories',entity.categories.join(', ')],['Industries',(entity.industries||[]).join(', ')],['Geography',entity.geographies.join(', ')],['Verification',entity.verification_status],['Last verified',entity.last_verified]].filter(([,value])=>value);
 const sections=[['Community formats',labels('community_formats',entity.community_formats)],['Event formats',labels('event_formats',entity.event_formats)],['Research & intelligence',labels('intelligence_types',entity.intelligence_types)],['Resources',labels('resource_types',entity.resource_types)],['Executive needs',labels('executive_needs',entity.executive_needs)],['Topics',labels('topics',entity.topics)],['Additional audiences',labels('audiences',entity.audiences)]];
 const semanticSections=sections.filter(([,values])=>values.length).map(([heading,values])=>`<section><h2>${heading}</h2><div class="tags large">${values.map(value=>`<span>${esc(value)}</span>`).join('')}</div></section>`).join('');
 const sources=[...entity.sources.map(x=>({id:x.id,url:x.url,title:x.title,detail:`${x.publisher} · accessed ${x.accessed_date} · supports ${x.supports.join(', ')}`})),...entity.classification_evidence.map((x,index)=>({id:`classification-source-${index+1}`,url:x.url,title:x.title,detail:`classification evidence · supports ${x.supports.join(', ')}`}))];
 const sourceList=sources.map(source=>`<li id="${esc(source.id||'classification-source')}"><a href="${esc(source.url)}">${esc(source.title)}</a><span>${esc(source.detail)}</span></li>`).join('');
 const factRows=(entity.facts||[]).map(fact=>`<tr><td>${esc(fact.field.replaceAll('_',' '))}</td><td>${esc(Array.isArray(fact.value)?fact.value.join(', '):fact.value)}</td><td>${fact.source_ids.map(id=>`<a href="#${esc(id)}">${esc(id)}</a>`).join(', ')}</td><td>${esc(fact.last_verified)}</td></tr>`).join('');
 const jsonld=JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:entity.name,alternateName:entity.aliases||[],url:entity.website,description:entity.description,areaServed:entity.geographies,knowsAbout:labels('topics',entity.topics).length?labels('topics',entity.topics):entity.categories,parentOrganization:entity.parent_company?{'@type':'Organization',name:entity.parent_company}:undefined});
 const body=`<nav class="crumb"><a href="../index.html">Index</a> / ${esc(entity.name)}</nav><section class="entity-head"><div class="eyebrow">${esc(entity.entity_type)}</div><h1>${esc(entity.name)}</h1><p>${esc(entity.description)}</p><a class="site-link" href="${esc(entity.website)}">Official website ↗</a></section><section class="entity-layout"><div><h2>Structured facts</h2><dl>${facts.map(([a,b])=>`<dt>${a}</dt><dd>${esc(b)}</dd>`).join('')}</dl></div><div><h2>Inclusion basis</h2><p>${esc(entity.inclusion_basis.join(' '))}</p><h2>Products and services</h2><p>${esc([...(entity.products||[]),...(entity.services||[])].join(', ')||'Not recorded.')}</p></div></section><div class="semantic-sections">${semanticSections}</div><section><h2>Source-linked facts</h2><p>${entity.facts.length} structured facts are linked to the supporting source record and verification date.</p><div class="table-wrap"><table><thead><tr><th>Field</th><th>Value</th><th>Source ID</th><th>Verified</th></tr></thead><tbody>${factRows}</tbody></table></div></section><section><h2>Sources</h2><ul class="sources">${sourceList}</ul></section><script type="application/ld+json">${jsonld}</script>`;
 await write(`docs/entities/${entity.slug}.html`,shell(`Entity: ${entity.name}`,body,entity.description,`${entity.name} | ${entity.categories.slice(0,2).join(' & ')}`));
}

const cfoEntities=entities.filter(entity=>entity.cxo_roles.includes('CFO'));
const topicList=items=>`<div class="topic-grid">${items.map(item=>`<span>${esc(typeof item==='string'?item:item.name)}</span>`).join('')}</div>`;
await write('docs/cfo-ecosystem.html',shell('CFO Ecosystem',`<section class="prose wide"><div class="eyebrow">EXPLORE BY CXO</div><h1>CFO Ecosystem</h1><p>A structured view of the companies, advisors, capital providers, communities, and technology platforms serving chief financial officers and finance organizations.</p><div class="stats compact"><div><strong>${cfoEntities.length}</strong><span>CFO-relevant entities</span></div><div><strong>${new Set(cfoEntities.flatMap(e=>e.categories)).size}</strong><span>Provider categories</span></div><div><strong>${new Set(cfoEntities.flatMap(e=>e.geographies)).size}</strong><span>Markets represented</span></div></div><h2>Operating contexts</h2>${topicList(cfoTaxonomy.contexts)}<h2>Finance functions</h2>${topicList(cfoTaxonomy.functional_topics)}<h2>Systems and transformation</h2>${topicList(cfoTaxonomy.systems_topics)}<h2>Decision resources</h2>${topicList(cfoTaxonomy.decision_resources)}<h2>Indexed organizations</h2><div class="grid">${cfoEntities.map(entityCard).join('')}</div></section>`,'Structured intelligence on providers, systems, capital, communities, and advisors serving CFOs.'));
const rolePages=[
 {label:'CEO',roles:['CEO'],description:'Chief executives responsible for enterprise strategy, leadership, capital, growth, and board accountability.'},
 {label:'CMO',roles:['CMO'],description:'Chief marketing officers responsible for market strategy, customer acquisition, brand, growth, and marketing performance.'},
 {label:'CISO',roles:['CISO'],description:'Chief information security officers responsible for cybersecurity strategy, identity, risk, resilience, and board reporting.'},
 {label:'CIO & CTO',roles:['CIO','CTO'],description:'Technology executives responsible for enterprise systems, data, artificial intelligence, architecture, engineering, and technology strategy.'},
 {label:'CHRO',roles:['CHRO'],description:'People executives responsible for workforce strategy, talent, human resources, benefits, performance, and organizational development.'},
 {label:'CLO & General Counsel',roles:['CLO','General Counsel'],description:'Senior legal executives responsible for corporate law, governance, transactions, regulation, disputes, privacy, and legal operations.'},
 {label:'COO',roles:['COO'],description:'Operating executives responsible for organizational execution, processes, systems, delivery, and performance.'},
 {label:'Board',roles:['Board'],description:'Board directors and governance leaders responsible for oversight, accountability, succession, risk, and long-term enterprise stewardship.'}
];
for(const group of rolePages){const roleEntities=entities.filter(entity=>group.roles.some(role=>entity.cxo_roles.includes(role)));const roleSlug=slug(group.label);await write(`docs/${roleSlug}-ecosystem.html`,shell(`${group.label} Ecosystem`,`<section class="prose wide"><div class="eyebrow">EXPLORE BY CXO</div><h1>${group.label} Ecosystem</h1><p>${esc(group.description)}</p><p>This canonical role page contains ${roleEntities.length} evidence-backed organizations across ${new Set(roleEntities.flatMap(e=>e.categories)).size} provider categories. Related titles are normalized into one functional hub where appropriate.</p><div class="grid">${roleEntities.map(entityCard).join('')}</div></section>`,`Structured index of organizations serving ${group.label} leaders.`));}
const roleLinks=[{label:'CFO',href:'cfo-ecosystem.html',count:cfoEntities.length},...rolePages.map(group=>({label:group.label,href:`${slug(group.label)}-ecosystem.html`,count:entities.filter(entity=>group.roles.some(role=>entity.cxo_roles.includes(role))).length}))];
await write('docs/cxo-ecosystems.html',shell('CXO Ecosystems',`<section class="prose wide"><div class="eyebrow">FUNCTIONAL ECOSYSTEMS</div><h1>CXO Ecosystems</h1><p>Browse evidence-backed provider landscapes by executive function. CLO and General Counsel are normalized into one legal-leadership ecosystem; CIO and CTO share one technology-leadership ecosystem.</p><div class="grid">${roleLinks.map(item=>`<article class="card"><h3><a href="${item.href}">${esc(item.label)} Ecosystem</a></h3><p>${item.count} indexed organizations.</p></article>`).join('')}</div></section>`,'Evidence-backed provider ecosystems for executive functions.'));

for(const group of providerGroups){
 const label=termTitle(group.id);const roles=[...new Set(group.entities.flatMap(entity=>entity.cxo_roles))];const markets=[...new Set(group.entities.flatMap(entity=>entity.geographies))];
 const primaryCount=group.entities.filter(entity=>entity.sources.some(source=>['official company','official organization','government','regulatory','investor relations'].includes(source.source_class))).length;
 const aiCount=group.entities.filter(entity=>entity.categories.some(category=>['Artificial Intelligence','AI Agents','AI Infrastructure','AI Security'].includes(category))).length;
 const roleCounts=Object.entries(Object.groupBy(group.entities.flatMap(entity=>entity.cxo_roles),role=>role)).map(([role,items])=>[role,items.length]).sort((a,b)=>b[1]-a[1]);
 const subcategoryCounts=Object.entries(Object.groupBy(group.entities.flatMap(entity=>entity.categories.filter(category=>slug(category)!==group.id)),category=>category)).map(([category,items])=>[category,items.length]).sort((a,b)=>b[1]-a[1]).slice(0,8);
 const body=`<section class="prose wide"><div class="eyebrow">PROVIDER TYPE</div><h1>${esc(label)}</h1><p>An evidence-backed view of organizations classified as ${esc(label.toLowerCase())} providers in the CXO Ecosystem Index.</p><div class="stats compact"><div><strong>${group.entities.length}</strong><span>Organizations</span></div><div><strong>${Math.round(100*primaryCount/group.entities.length)}%</strong><span>Primary-source coverage</span></div><div><strong>${aiCount}</strong><span>AI-related providers</span></div></div><h2>Category intelligence</h2><p><b>CXO-role distribution:</b> ${roleCounts.map(([role,count])=>`${esc(role)} ${count}`).join(' · ')}</p><p><b>Common adjacent categories:</b> ${subcategoryCounts.map(([category,count])=>`${esc(category)} ${count}`).join(' · ')||'No adjacent category recorded.'}</p><p><small>Statistics use dataset version 0.5.0, calculation date 2026-08-11, and all ${group.entities.length} indexed organizations in this category as the denominator. Unknown fields are not inferred.</small></p><h2>Indexed organizations</h2><div class="grid">${group.entities.map(entityCard).join('').replaceAll('href="entities/','href="../entities/')}</div><p><small>Inclusion is neutral and does not imply endorsement. Category membership requires cited evidence on each organization page.</small></p></section>`;
 await write(`docs/providers/${group.id}.html`,shell(`Provider: ${label}`,body,`Evidence-backed index of ${label.toLowerCase()} organizations serving executives.`));
}
for(const group of formatGroups){
 const term=vocab.get(`community_formats:${group.id}`);const label=term?.label||termTitle(group.id);
 const body=`<section class="prose wide"><div class="eyebrow">COMMUNITY FORMAT</div><h1>${esc(label)}</h1><p>${esc(term?.definition||`Organizations offering the ${label.toLowerCase()} format.`)}</p><p>This canonical format page includes ${group.entities.length} evidence-backed organizations. Narrower role, topic, need, and geography combinations remain filters.</p><h2>Indexed organizations</h2><div class="grid">${group.entities.map(entityCard).join('').replaceAll('href="entities/','href="../entities/')}</div><p><small>Format classification requires cited evidence on each organization page.</small></p></section>`;
 await write(`docs/formats/${group.id}.html`,shell(`Format: ${label}`,body,`Organizations offering the ${label.toLowerCase()} format.`));
}

const guideCards=cfoGuides.map(guide=>`<article class="card"><div class="eyebrow">CFO GUIDE</div><h3><a href="guides/${guide.slug}.html">${esc(guide.title)}</a></h3><p>${esc(guide.summary)}</p><small>Updated ${esc(guide.updated)}</small></article>`).join('');
await write('docs/cfo-guides.html',shell('CFO Guides',`<section class="prose wide"><div class="eyebrow">ORIGINAL DECISION RESOURCES</div><h1>CFO guides</h1><p>Evidence-backed, vendor-neutral resources generated from structured source records.</p><div class="grid">${guideCards}</div></section>`,'Evidence-backed, vendor-neutral decision resources for CFOs.'));
for(const guide of cfoGuides){
 const sections=guide.sections.map(section=>`<section><h2>${esc(section.heading)}</h2><p>${esc(section.content)}</p>${section.bullets?`<ul>${section.bullets.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`:''}</section>`).join('');
 const sources=guide.sources.map(source=>`<li><a href="${esc(source.url)}">${esc(source.title)}</a><span>${esc(source.publisher)}</span></li>`).join('');
 await write(`docs/guides/${guide.slug}.html`,shell(`Guide: ${guide.title}`,`<nav class="crumb"><a href="../cfo-guides.html">CFO guides</a> / ${esc(guide.title)}</nav><article class="prose"><div class="eyebrow">CFO DECISION RESOURCE</div><h1>${esc(guide.title)}</h1><p>${esc(guide.summary)}</p><p><b>Audience:</b> ${esc(guide.audience.join(', '))} · <b>Updated:</b> ${esc(guide.updated)}</p>${sections}<h2>Primary sources</h2><ul class="sources">${sources}</ul><p><small>This guide is educational and does not replace accounting, legal, security, or audit advice.</small></p></article>`,guide.summary));
}

await write('docs/methodology.html',shell('Methodology',`<section class="prose"><div class="eyebrow">TRUST AND GOVERNANCE</div><h1>Methodology</h1><h2>Classification model</h2><p>Organizations are classified independently across executive roles, provider types, community formats, event formats, intelligence types, resources, executive needs, topics, and geographies. A multi-category organization retains one canonical entity record.</p><h2>Controlled vocabulary</h2><p>Every semantic term has a stable ID and neutral definition. Closely related phrases map to one canonical concept unless they represent a material distinction.</p><h2>Evidence requirement</h2><p>Entity associations require reasonable evidence from official organization, event, research, regulatory, government, or reputable third-party sources. A passing keyword mention is insufficient.</p><h2>Indexability gate</h2><p>Arbitrary filter combinations remain application state. A canonical page is created only when it has stable intent, enough substantive entities, distinct analysis, and durable value.</p><h2>Commercial neutrality</h2><p>Inclusion does not constitute endorsement. Commercial relationships do not influence inclusion, ranking, scoring, descriptions, or category placement.</p><h2>Versioning</h2><p>Schema and dataset versions are published in exports. Stable IDs do not change without a documented migration.</p></section>`));
const added=expansion.entities.filter(item=>item.status==='added');const unresolved=expansion.entities.filter(item=>item.status==='unresolved');
const reportRows=items=>items.map(item=>`<tr><td>${esc(item.name)}</td><td>${esc(item.priority||'')}</td><td>${esc(item.status)}</td><td>${esc(item.reason||item.relationship_notes||'Verified from the official organization website.')}</td></tr>`).join('');
await write('docs/reconciliation-report.html',shell('Expansion Reconciliation Report',`<section class="prose wide"><div class="eyebrow">DATASET EXPANSION AUDIT</div><h1>Organization reconciliation report</h1><p>Every supplied organization or alias was assigned a visible state. Priority indicates editorial research order, not rank, quality, sponsorship, or endorsement.</p><div class="stats compact"><div><strong>51</strong><span>Organizations before</span></div><div><strong>${entities.length}</strong><span>Organizations after</span></div><div><strong>${added.length}</strong><span>New canonical entities</span></div></div><h2>Duplicates and aliases resolved</h2><ul>${expansion.duplicate_aliases.map(item=>`<li><b>${esc(item.supplied)}</b> → ${esc(item.canonical)}</li>`).join('')}</ul><h2>Added</h2><div class="table-wrap"><table><thead><tr><th>Organization</th><th>Priority</th><th>Status</th><th>Resolution</th></tr></thead><tbody>${reportRows(added)}</tbody></table></div><h2>Unresolved</h2><p>These names remain in the research queue because assigning a canonical entity without further evidence would risk a false match.</p><div class="table-wrap"><table><thead><tr><th>Supplied name</th><th>Priority</th><th>Status</th><th>Reason</th></tr></thead><tbody>${reportRows(unresolved)}</tbody></table></div><h2>Validation statement</h2><p><b>Every name supplied in the expansion brief has been accounted for</b> as an added canonical entity, merged alias, repeated multi-category reference, or unresolved research item. No name was silently omitted.</p></section>`,'Audit trail for the August 2026 CXO Ecosystem Index organization expansion.'));
const resolutionRows=resolutionV050.map(item=>`<tr><td>${esc(item.original)}</td><td>${esc(item.canonical)}</td><td><a href="https://${esc(item.domain)}">${esc(item.domain)}</a></td><td>${esc(item.result)}</td><td>${esc(item.category)}</td><td>${esc(item.confidence)}</td></tr>`).join('');
await write('docs/v050-report.html',shell('v050 Report',`<section class="prose wide"><div class="eyebrow">RELEASE AUDIT</div><h1>v0.5.0 Fact Depth & Entity Resolution</h1><div class="stats compact"><div><strong>175</strong><span>Organizations before</span></div><div><strong>${entities.length}</strong><span>Organizations after</span></div><div><strong>${s.sourced_facts}</strong><span>Sourced facts</span></div><div><strong>${s.facts_per_entity}</strong><span>Facts per entity</span></div><div><strong>${s.primary_source_coverage}%</strong><span>Primary-source coverage</span></div></div><h2>Former unresolved entities</h2><p>All 18 former unresolved names now have an explicit canonical resolution. Claims are limited to what the cited official source supports.</p><div class="table-wrap"><table><thead><tr><th>Original</th><th>Canonical entity</th><th>Domain</th><th>Resolution</th><th>Category</th><th>Confidence</th></tr></thead><tbody>${resolutionRows}</tbody></table></div><h2>Fact methodology</h2><p>A sourced fact is one explicit field/value assertion connected to at least one source ID and a last-verified date. Array values such as executive roles and provider categories count individually because each is independently queryable. Missing values are omitted. Volatile values require an as-of date and are not inferred.</p></section>`,'v0.5.0 release report covering fact depth and resolution of 18 former unresolved organizations.','v0.5.0 Fact Depth Report'));
const datasetLd=JSON.stringify({'@context':'https://schema.org','@type':'Dataset',name:'CXO Ecosystem Index',description:'Open-source structured intelligence on organizations serving executive functions.',version:'0.5.0',dateModified:'2026-08-11',creator:{'@type':'Organization',name:'Open Future Forum'},license:'https://opensource.org/license/mit/',distribution:[{'@type':'DataDownload',encodingFormat:'application/json',contentUrl:'https://openfutureforum.github.io/cxo-ecosystem-index/data/entities.json'},{'@type':'DataDownload',encodingFormat:'text/csv',contentUrl:'https://openfutureforum.github.io/cxo-ecosystem-index/data/entities.csv'}]});
await write('docs/data.html',shell('Data',`<section class="prose wide"><div class="eyebrow">OPEN DATA</div><h1>Download the dataset</h1><p>Exports are generated from canonical records during every build.</p><div class="download"><a href="data/entities.json">Entities JSON</a><a href="data/entities.csv">Entities CSV</a><a href="data/taxonomy.json">Taxonomy JSON</a><a href="data/statistics.json">Statistics JSON</a><a href="data/definitions.json">Definitions JSON</a></div><h2>Data quality dashboard</h2><div class="stats compact"><div><strong>${s.entities}</strong><span>Organizations</span></div><div><strong>${s.sourced_facts}</strong><span>Sourced facts</span></div><div><strong>${s.facts_per_entity}</strong><span>Facts per entity</span></div><div><strong>${s.primary_source_coverage}%</strong><span>Primary-source coverage</span></div><div><strong>${s.average_sources_per_entity}</strong><span>Sources per entity</span></div><div><strong>${s.verified_within_12_months}</strong><span>Verified within 12 months</span></div></div><h2>Dataset metadata</h2><dl><dt>Dataset version</dt><dd>0.5.0</dd><dt>Schema version</dt><dd>2.2.0</dd><dt>Modified</dt><dd>2026-08-11</dd><dt>Creator</dt><dd>Open Future Forum</dd><dt>License</dt><dd>MIT</dd><dt>Coverage</dt><dd>Representative dataset; global coverage is not claimed.</dd><dt>Volatile facts with as-of date</dt><dd>${s.volatile_facts_with_as_of_date}</dd><dt>Relationship records</dt><dd>${s.relationship_records}</dd><dt>Unresolved entities</dt><dd>${unresolved.length}</dd></dl><h2>Fact model</h2><p>Each source-linked fact records a field, value, source ID, and last-verified date. Volatile facts additionally support an as-of date. Unknown values are omitted rather than inferred.</p><p><a href="reconciliation-report.html">Expansion reconciliation report</a></p><script type="application/ld+json">${datasetLd}</script></section>`));

const urls=['','cxo-ecosystems.html','cfo-ecosystem.html',...rolePages.map(group=>`${slug(group.label)}-ecosystem.html`),'cfo-guides.html',...cfoGuides.map(g=>`guides/${g.slug}.html`),...providerGroups.map(group=>`providers/${group.id}.html`),...formatGroups.map(group=>`formats/${group.id}.html`),'reconciliation-report.html','v050-report.html','methodology.html','data.html',...entities.map(e=>`entities/${e.slug}.html`)];
await write('docs/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(url=>`<url><loc>https://openfutureforum.github.io/cxo-ecosystem-index/${url}</loc><lastmod>2026-08-11</lastmod></url>`).join('')}</urlset>`);
await write('docs/robots.txt','User-agent: *\nAllow: /\nSitemap: https://openfutureforum.github.io/cxo-ecosystem-index/sitemap.xml\n');
await write('docs/llms.txt','# CXO Ecosystem Index\n\nIndependent structured index maintained by Open Future Forum. Inclusion does not imply endorsement.\n\nMaps: CXO roles; organizations; provider types; communities and networks; membership formats; event formats; research and benchmarks; decision resources; executive needs; leadership topics; and geographies.\n\nCanonical resources:\n- Entities: https://openfutureforum.github.io/cxo-ecosystem-index/data/entities.json\n- Taxonomy: https://openfutureforum.github.io/cxo-ecosystem-index/data/taxonomy.json\n- Statistics: https://openfutureforum.github.io/cxo-ecosystem-index/data/statistics.json\n- v0.5.0 report: https://openfutureforum.github.io/cxo-ecosystem-index/v050-report.html\n- Methodology: https://openfutureforum.github.io/cxo-ecosystem-index/methodology.html\n- Repository: https://github.com/OpenFutureForum/cxo-ecosystem-index\n\nEntity associations require evidence. Filter combinations are not canonical pages. Coverage is representative at dataset version 0.5.0.\n');
console.log(`Built ${entities.length} entity pages with semantic taxonomy version 2.0.0.`);
