import {slug} from './lib.mjs';

export const DATASET_VERSION='0.8.0';
export const CALCULATED_AT='2026-08-11';
const text=e=>JSON.stringify([e.description,e.categories,e.subcategories,e.products,e.services,e.topics,e.community_formats,e.event_formats,e.intelligence_types,e.resource_types]).toLowerCase();
const hasText=(e,terms)=>terms.some(term=>text(e).includes(term.toLowerCase()));
const matches=(e,rule={})=>(!rule.categories||rule.categories.some(x=>e.categories.includes(x)))&&(!rule.roles||rule.roles.some(x=>e.cxo_roles.includes(x)))&&(!rule.terms||hasText(e,rule.terms));
const metric=(id,name,numerator,denominator,{knownCount=denominator,unknownCount=0,scope={},definition='',method='',sourceFields=[],cohortIds=[],numeratorIds=[],unknownIds=[],excludedIds=[]}={})=>({id,name,value:denominator?Number((numerator/denominator).toFixed(4)):null,value_type:'percentage',unit:'share',numerator,denominator,known_count:knownCount,unknown_count:unknownCount,coverage:knownCount+unknownCount?Number((knownCount/(knownCount+unknownCount)).toFixed(4)):0,cohort_entity_ids:cohortIds,numerator_entity_ids:numeratorIds,unknown_entity_ids:unknownIds,excluded_entity_ids:excludedIds,scope,filters:scope,field_definition:definition,method,dataset_version:DATASET_VERSION,schema_version:'1.2.0',calculated_at:CALCULATED_AT,source_fields:sourceFields,notes:knownCount+unknownCount&&knownCount/(knownCount+unknownCount)<.6?'Data coverage insufficient for a reliable headline benchmark.':null});

const mapConfigs=[
 {id:'cfo-technology',title:'CFO Technology Market Map',definition:'Organizations explicitly classified as CFO Technology, organized by documented finance function.',cohort:{categories:['CFO Technology']},buckets:[['Spend Management',{categories:['Spend Management']}],['AP & Payments',{categories:['Payments']}],['Accounting, ERP & Close',{categories:['Accounting Software']}],['Treasury, Cash & AR',{categories:['Treasury Technology']}],['Tax',{categories:['Tax Technology']}],['Equity & Private Markets',{categories:['Equity Management','Private Market Infrastructure']}],['Banking & Finance Platforms',{categories:['Banking Platforms']}],['Finance AI',{categories:['Artificial Intelligence']}]]},
 {id:'ai-security',title:'AI Security Market Map',definition:'Organizations explicitly classified as AI Security, organized by documented security function.',cohort:{categories:['AI Security']},buckets:[['Agent Identity & Permissions',{categories:['Agent Identity','Identity and Access Management']}],['AI Governance & CISO Operations',{categories:['GRC Automation'],terms:['governance','ciso']}],['Agent Runtime Security',{categories:['Runtime Security']}],['AI Application Security',{categories:['Application Security']}],['AI Email Security',{categories:['Email Security']}],['AI Exposure & Governance',{terms:['exposure','governance','training']}],['Security Operations & MDR',{terms:['security operations','managed detection','mdr']}],['Synthetic Media Security',{terms:['deepfake','synthetic']}]]},
 {id:'executive-communities',title:'Executive Communities Market Map',definition:'Membership, peer and founder organizations classified as Executive Communities.',cohort:{categories:['Executive Communities']},buckets:[['CEO Peer Advisory',{roles:['CEO'],terms:['peer']}],['Founder Networks',{terms:['founder','entrepreneur']}],['Functional Executive Communities',{terms:['cfo','cmo','ciso','chro','revenue']}],['Private Capital & M&A Communities',{categories:['Professional Associations'],terms:['capital','m&a','merger']}],['Women Executive Networks',{terms:['women']}],['Future of Work & People Leadership',{roles:['CHRO'],terms:['people','work']}],['Curated Multi-CXO Communities',{terms:['multi-cxo','multiple c-suite','senior executives']}]]},
 {id:'executive-search',title:'Executive Search Market Map',definition:'Organizations providing retained search, recruiting, board search or talent intelligence.',cohort:{categories:['Executive Search','Recruiting']},buckets:[['Retained Executive Search',{categories:['Executive Search']}],['Technology-Enabled Talent Intelligence',{categories:['HR Technology','Artificial Intelligence']}],['Staffing & Professional Talent',{categories:['Recruiting'],terms:['staffing','professional']}],['Board Search',{terms:['board search','board advisory']}],['Private Equity Talent',{terms:['private equity']}],['Leadership Assessment & Succession',{terms:['leadership assessment','succession']}]]},
 {id:'technology-law-firms',title:'Technology Law Firm Landscape',definition:'Indexed law firms with documented technology, venture, private-equity, transaction, governance or privacy relevance.',cohort:{categories:['Law Firms']},buckets:[['Venture & Startup',{terms:['venture','startup']}],['Private Equity',{terms:['private equity']}],['M&A',{terms:['m&a','merger','acquisition','transactions']}],['Artificial Intelligence',{terms:['artificial intelligence','ai']}],['Cybersecurity & Privacy',{terms:['cybersecurity','privacy']}],['Technology Transactions',{terms:['technology transaction','technology']}],['Governance',{terms:['governance']}]]},
 {id:'banking-capital',title:'Banking & Capital Ecosystem Map',definition:'Banks and investment banks organized by documented business capabilities.',cohort:{categories:['Banks','Investment Banks']},buckets:[['Commercial Banking',{categories:['Banks'],terms:['commercial']}],['Venture & Startup Banking',{terms:['venture','startup','innovation']}],['Technology Banking',{terms:['technology banking','technology companies']}],['Treasury & Payments',{terms:['treasury','payments']}],['Lending & Venture Debt',{categories:['Venture Debt'],terms:['lending','credit']}],['Investment Banking',{categories:['Investment Banks']}],['Private Banking & Wealth',{categories:['Wealth Management']}]]},
 {id:'chro-technology',title:'CHRO Technology Market Map',definition:'Organizations classified as HR Technology and serving CHRO or workforce buyers.',cohort:{categories:['HR Technology']},buckets:[['HRIS & Workforce Management',{terms:['hris','workforce management','human resources']}],['Payroll',{terms:['payroll']}],['PEO',{terms:['professional employer','peo']}],['Employer of Record',{terms:['employer of record']}],['Recruiting & Talent Intelligence',{categories:['Recruiting'],terms:['recruiting','talent']}],['Performance Management',{terms:['performance management']}],['Benefits',{terms:['benefits']}],['HR AI',{categories:['Artificial Intelligence']}]]},
 {id:'enterprise-ai',title:'Enterprise AI Market Map',definition:'Enterprise-facing AI organizations organized by documented functional layer.',cohort:{categories:['Artificial Intelligence','AI Infrastructure','AI Agents']},buckets:[['Compute & AI Infrastructure',{categories:['AI Infrastructure'],terms:['compute','processor','accelerator']}],['Data & AI Platforms',{terms:['data platform','analytics','machine learning']}],['Enterprise AI Platforms',{categories:['Enterprise Technology'],terms:['enterprise']}],['Agent Platforms',{categories:['AI Agents']}],['Enterprise Search & Knowledge',{terms:['search','knowledge']}],['Automation',{categories:['Enterprise Automation'],terms:['automation','workflow']}],['Domain-Specific AI',{terms:['legal','finance','marketing','security','semiconductor']}],['Semiconductor & Engineering AI',{categories:['Semiconductor Technology','Electronic Design Automation']}]]}
];

export function buildMarketMaps(entities){return mapConfigs.map(config=>{const cohort=entities.filter(e=>matches(e,config.cohort));const buckets=config.buckets.map(([name,rule])=>{const members=cohort.filter(e=>matches(e,rule));return {id:slug(name),name,count:members.length,share:cohort.length?Number((members.length/cohort.length).toFixed(4)):0,entity_ids:members.map(e=>e.id)};}).filter(bucket=>bucket.count);const covered=new Set(buckets.flatMap(b=>b.entity_ids));return {id:config.id,title:config.title,definition:config.definition,dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,total_entities:cohort.length,known_count:covered.size,unknown_count:cohort.length-covered.size,coverage:cohort.length?Number((covered.size/cohort.length).toFixed(4)):0,buckets,entity_ids:cohort.map(e=>e.id),source_fields:['categories','subcategories','products','services','description','cxo_roles']};});}

const comparisonConfigs=[
 {id:'cfo-spend-platforms',title:'CFO Spend & Finance Platforms',names:['Ramp','Brex','Coupa','BILL'],dimensions:[['Provider categories','categories'],['CXO audience','cxo_roles'],['Spend management','spend management'],['Corporate cards','corporate card'],['AP automation','accounts payable'],['Procurement','procurement'],['Payments','payments'],['AI capability','artificial intelligence']]},
 {id:'accounting-close-systems',title:'Accounting, Close & Finance Systems',names:['BlackLine','Puzzle','Rillet','Xero','Intuit','Pilot'],dimensions:[['Provider categories','categories'],['Accounting system','accounting'],['Financial close','close'],['Bookkeeping service','bookkeeping'],['ERP','enterprise-resource-planning'],['Automation','automation'],['AI capability','artificial intelligence']]},
 {id:'executive-communities',title:'Executive Communities',names:['Vistage','YPO',"Entrepreneurs' Organization",'Chief','Open Future Forum'],dimensions:[['CXO audience','cxo_roles'],['Community formats','community_formats'],['Application required','application_required'],['Invite-only components','invite_only'],['Peer groups','peer group'],['Private events','private'],['Research','research'],['Geography','geographies']]},
 {id:'executive-search-firms',title:'Executive Search Firms',names:['Korn Ferry','Spencer Stuart','Russell Reynolds Associates','Heidrick & Struggles','ZRG'],dimensions:[['CXO audience','cxo_roles'],['Provider categories','categories'],['Board search','board'],['Private equity talent','private equity'],['Succession','succession'],['Leadership assessment','leadership assessment'],['Geography','geographies']]},
 {id:'technology-law-firms',title:'Technology Law Firms',names:['Wilson Sonsini Goodrich & Rosati','Cooley','Fenwick & West','Foley & Lardner','Orrick','DLA Piper'],dimensions:[['Provider categories','categories'],['Startup & venture','venture'],['Private equity','private equity'],['M&A','m&a'],['AI','artificial intelligence'],['Cybersecurity & privacy','privacy'],['Technology transactions','technology'],['Geography','geographies']]},
 {id:'technology-venture-banking',title:'Technology & Venture Banking',names:['Silicon Valley Bank','First Citizens Bank','Comerica','Stifel','BMO','Wells Fargo','Citizens Private Bank'],dimensions:[['Provider categories','categories'],['Startup banking','startup'],['Venture-backed focus','venture'],['Technology banking','technology'],['Treasury','treasury'],['Credit & lending','lending'],['Private banking','private banking'],['Geography','geographies']]}
];
const resolveName=(entities,name)=>entities.find(e=>e.name===name||e.aliases?.includes(name));
export function buildComparisons(entities){return comparisonConfigs.map(config=>{const cohort=config.names.map(name=>resolveName(entities,name)).filter(Boolean);return {comparison_id:config.id,title:config.title,dataset_version:DATASET_VERSION,generated_at:CALCULATED_AT,entity_ids:cohort.map(e=>e.id),dimensions:config.dimensions.map(([label,spec])=>{const id=slug(label);const values={};for(const e of cohort){if(['categories','cxo_roles','community_formats','geographies'].includes(spec))values[e.id]=(e[spec]||[]).length?(e[spec]||[]):['Not verified'];else if(['application_required','invite_only'].includes(spec))values[e.id]=e[spec]===true?'Verified':e[spec]===false?'Not applicable':'Not verified';else values[e.id]=hasText(e,[spec])?'Verified':'Not verified';}return {id,label,fact_field:spec,comparability_rule:'Values originate from canonical fields; absence of evidence is shown as Not verified.',values};})};});}

const knownField=(e,field)=>e.sources.some(source=>source.supports?.includes(field));
export function buildBenchmarks(entities){
 const ageKnown=entities.filter(e=>knownField(e,'founded_year')&&Number.isFinite(e.founded_year));const pricingKnown=entities.filter(e=>knownField(e,'public_pricing'));const geographyKnown=entities.filter(e=>knownField(e,'headquarters'));
 const aiCategories=['Artificial Intelligence','AI Agents','AI Infrastructure','AI Security'];const aiScopes=['CFO Technology','HR Technology','Enterprise Technology','Cybersecurity','Consulting','Executive Search','Legal Technology'];
 const aiMetrics=aiScopes.map(category=>{const cohort=entities.filter(e=>e.categories.includes(category));const known=cohort.filter(e=>knownField(e,'categories'));const yes=known.filter(e=>e.categories.some(x=>aiCategories.includes(x)));const unknown=cohort.filter(e=>!known.includes(e));return metric(`ai-${slug(category)}`,`${category}: documented AI capability`,yes.length,known.length,{knownCount:known.length,unknownCount:unknown.length,cohortIds:cohort.map(e=>e.id),numeratorIds:yes.map(e=>e.id),unknownIds:unknown.map(e=>e.id),scope:{category},definition:'Current canonical category evidence explicitly includes an AI product or service category.',method:'Count AI-classified entities among records with sourced category classification.',sourceFields:['categories']});});
 const roleCounts=Object.entries(Object.groupBy(entities.flatMap(e=>e.cxo_roles),role=>role)).map(([role,items])=>({role,count:items.length})).sort((a,b)=>b.count-a.count);
 const qualityFacts=entities.map(e=>e.facts.length).sort((a,b)=>a-b);const median=qualityFacts.length?qualityFacts[Math.floor(qualityFacts.length/2)]:0;const conflictingFacts=entities.flatMap(e=>e.facts).filter(f=>f.verification_status==='conflicting').length;const now=Date.parse(CALCULATED_AT);const staleFacts=entities.flatMap(e=>e.facts).filter(f=>now-Date.parse(f.last_verified)>365*86400000).length;
 return [
  {id:'ai-capability',title:'AI Capability Benchmark',dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,metrics:aiMetrics,entity_ids:entities.map(e=>e.id)},
  {id:'company-age',title:'Company Age & Founding Benchmark',dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,known_count:ageKnown.length,unknown_count:entities.length-ageKnown.length,coverage:Number((ageKnown.length/entities.length).toFixed(4)),status:ageKnown.length/entities.length<.6?'insufficient coverage':'usable',method:'Only source-supported founding_year values are eligible.',source_fields:['founded_year'],cohort_entity_ids:entities.map(e=>e.id),entity_ids:ageKnown.map(e=>e.id),unknown_entity_ids:entities.filter(e=>!ageKnown.includes(e)).map(e=>e.id),excluded_entity_ids:[]},
  {id:'geographic-concentration',title:'Geographic Concentration Benchmark',dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,known_count:geographyKnown.length,unknown_count:entities.length-geographyKnown.length,coverage:Number((geographyKnown.length/entities.length).toFixed(4)),status:geographyKnown.length/entities.length<.6?'insufficient coverage':'usable',method:'Headquarters is kept separate from office and service geography; only sourced headquarters fields qualify.',source_fields:['headquarters'],cohort_entity_ids:entities.map(e=>e.id),entity_ids:geographyKnown.map(e=>e.id),unknown_entity_ids:entities.filter(e=>!geographyKnown.includes(e)).map(e=>e.id),excluded_entity_ids:[]},
  {id:'pricing-transparency',title:'Pricing Transparency Benchmark',dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,known_count:pricingKnown.length,unknown_count:entities.length-pricingKnown.length,coverage:Number((pricingKnown.length/entities.length).toFixed(4)),status:pricingKnown.length/entities.length<.6?'insufficient coverage':'usable',method:'Missing public pricing is unknown, not false.',source_fields:['public_pricing'],cohort_entity_ids:entities.map(e=>e.id),entity_ids:pricingKnown.map(e=>e.id),unknown_entity_ids:entities.filter(e=>!pricingKnown.includes(e)).map(e=>e.id),excluded_entity_ids:[]},
  {id:'c-suite-coverage',title:'C-Suite Coverage Benchmark',dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,total_entities:entities.length,exactly_one:entities.filter(e=>e.cxo_roles.length===1).length,two_to_three:entities.filter(e=>e.cxo_roles.length>=2&&e.cxo_roles.length<=3).length,four_plus:entities.filter(e=>e.cxo_roles.length>=4).length,role_distribution:roleCounts,method:'Counts canonical cxo_roles classifications. CLO and General Counsel remain sub-role tags but share one navigation hub.',source_fields:['cxo_roles'],entity_ids:entities.map(e=>e.id)},
  {id:'data-quality',title:'Source & Data Quality Benchmark',dataset_version:DATASET_VERSION,calculated_at:CALCULATED_AT,total_entities:entities.length,total_facts:qualityFacts.reduce((a,b)=>a+b,0),average_facts_per_entity:Number((qualityFacts.reduce((a,b)=>a+b,0)/entities.length).toFixed(2)),median_facts_per_entity:median,entities_with_3_plus:qualityFacts.filter(n=>n>=3).length,entities_with_5_plus:qualityFacts.filter(n=>n>=5).length,entities_with_10_plus:qualityFacts.filter(n=>n>=10).length,entities_with_20_plus:qualityFacts.filter(n=>n>=20).length,entities_needing_enrichment:qualityFacts.filter(n=>n<5).length,verified_entities:entities.filter(e=>e.verification_status==='verified').length,verified_within_12_months:entities.filter(e=>now-Date.parse(e.last_verified)<=365*86400000).length,missing_headquarters:entities.filter(e=>!e.headquarters).length,missing_founding_year:entities.filter(e=>!Number.isFinite(e.founded_year)).length,conflicting_facts:conflictingFacts,stale_facts:staleFacts,primary_source_entities:entities.filter(e=>e.sources.some(s=>['official company','official organization','government','regulatory','investor relations'].includes(s.source_class))).length,volatile_facts_with_as_of_date:entities.reduce((n,e)=>n+e.facts.filter(f=>f.as_of_date).length,0),fact_distribution:[['0–2',qualityFacts.filter(n=>n<=2).length],['3–5',qualityFacts.filter(n=>n>=3&&n<=5).length],['6–10',qualityFacts.filter(n=>n>=6&&n<=10).length],['11–20',qualityFacts.filter(n=>n>=11&&n<=20).length],['20+',qualityFacts.filter(n=>n>=20).length]],source_fields:['facts','sources','last_verified','headquarters','founded_year','verification_status']}
 ];
}

export function buildIntelligence(entities){return {dataset_version:DATASET_VERSION,schema_version:'1.2.0',calculated_at:CALCULATED_AT,market_maps:buildMarketMaps(entities),comparisons:buildComparisons(entities),benchmarks:buildBenchmarks(entities)};}
